In [1]:
import pandas as pd
import sqlite3
#Analize it and also write it into a datase

In [2]:
titanic = "datasets/titanic.xls"
df = pd.read_excel(titanic)

In [3]:
df

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,3,0,"Zabour, Miss. Hileni",female,14.5000,1,0,2665,14.4542,NaN,C,NaN,328.0,NaN
1305,3,0,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,NaN,NaN,NaN
1306,3,0,"Zakarian, Mr. Mapriededer",male,26.5000,0,0,2656,7.2250,NaN,C,NaN,304.0,NaN
1307,3,0,"Zakarian, Mr. Ortin",male,27.0000,0,0,2670,7.2250,NaN,C,NaN,NaN,NaN
1308,3,0,"Zimmerman, Mr. Leo",male,29.0000,0,0,315082,7.8750,NaN,S,NaN,NaN,NaN

In [4]:
df.columns

Index(['pclass', 'survived', 'name', 'sex', 'age', 'sibsp', 'parch', 'ticket',
       'fare', 'cabin', 'embarked', 'boat', 'body', 'home.dest'],
      dtype='object')

In [5]:
df.dtypes

pclass         int64
survived       int64
name          object
sex           object
age          float64
sibsp          int64
parch          int64
ticket        object
fare         float64
cabin         object
embarked      object
boat          object
body         float64
home.dest     object
dtype: object

In [6]:
# get the number of persons per class
ppc = df.groupby("pclass")["name"].count()
ppc

pclass
1    323
2    277
3    709
Name: name, dtype: int64

In [7]:
# get the number of persons tht servived per class
spc = df.groupby("pclass")["survived"].sum()
spc

pclass
1    200
2    119
3    181
Name: survived, dtype: int64

In [8]:
survival_rate = round(spc / ppc * 100, 1)
print(survival_rate)
srdf = pd.DataFrame({"persons per class":ppc, "survived per class":spc, "survival rate per class (%)": survival_rate})
print(srdf)

pclass
1    61.9
2    43.0
3    25.5
dtype: float64
        persons per class  survived per class  survival rate per class (%)
pclass
1                     323                 200                         61.9
2                     277                 119                         43.0
3                     709                 181                         25.5

In [9]:
median_age = df["age"].median()
mean_age = df["age"].mean()
median_age_to_survive = df.groupby("survived")["age"].median()
mean_age_to_survive = df.groupby("survived")["age"].mean()
print("age on the boat:")
print(mean_age)
print(median_age)
print("age to survive:")
print(mean_age_to_survive)
print(median_age_to_survive)

# age does not matter

age on the boat:
29.8811345124283
28.0
age to survive:
survived
0    30.545369
1    28.918228
Name: age, dtype: float64
survived
0    28.0
1    28.0
Name: age, dtype: float64

In [10]:
max_ticket_price = df["fare"].max()
min_ticket_price = df["fare"].min()
print("cheapest ticket:", min_ticket_price)
print("most expensive ticket:", max_ticket_price)

median_tickt_price=df.groupby("pclass")["fare"].median()
mean_tickt_price=df.groupby("pclass")["fare"].mean()
print("avarage cost of a ticket in each class: (median):")
print(median_tickt_price)
print("avarage cost of a ticket in each class: (mean)")
print(mean_tickt_price)

cheapest ticket: 0.0
most expensive ticket: 512.3292
avarage cost of a ticket in each class: (median):
pclass
1    60.0000
2    15.0458
3     8.0500
Name: fare, dtype: float64
avarage cost of a ticket in each class: (mean)
pclass
1    87.508992
2    21.179196
3    13.302889
Name: fare, dtype: float64

In [11]:
mean_price_to_survive=df.groupby("survived")["fare"].mean()
median_price_to_survive=df.groupby("survived")["fare"].median()
print("what you pay to survive: (median)")
print(median_price_to_survive)
print("what you pay to survive: (mean)")
print(mean_price_to_survive)

what you pay to survive: (median)
survived
0    10.5
1    26.0
Name: fare, dtype: float64
what you pay to survive: (mean)
survived
0    23.353831
1    49.361184
Name: fare, dtype: float64

In [12]:
# age in class
median_age_in_class = df.groupby("pclass")["age"].median()
mean_age_in_class = df.groupby("pclass")["age"].mean()
print(median_age_in_class)
print(mean_age_in_class)

pclass
1    39.0
2    29.0
3    24.0
Name: age, dtype: float64
pclass
1    39.159918
2    29.506705
3    24.816367
Name: age, dtype: float64

In [27]:
# oldest person on board:
oldest = df["age"].max()
# youngest person on board:
youngest = df["age"].min()
# average age on board:
mean = df["age"].mean()
median = df["age"].median()
std = df["age"].std()
print("oldest:", oldest, "youngest:", youngest, "  - avg age (mean, median):", mean, median, std)

oldest: 80.0 youngest: 0.1667   - avg age (mean, median): 29.8811345124283 28.0 14.413499699923594

In [14]:
df.describe()

,pclass,survived,age,sibsp,parch,fare,body
count,1309.000000,1309.000000,1046.000000,1309.000000,1309.000000,1308.000000,121.000000
mean,2.294882,0.381971,29.881135,0.498854,0.385027,33.295479,160.809917
std,0.837836,0.486055,14.413500,1.041658,0.865560,51.758668,97.696922
min,1.000000,0.000000,0.166700,0.000000,0.000000,0.000000,1.000000
25%,2.000000,0.000000,21.000000,0.000000,0.000000,7.895800,72.000000
50%,3.000000,0.000000,28.000000,0.000000,0.000000,14.454200,155.000000
75%,3.000000,1.000000,39.000000,1.000000,0.000000,31.275000,256.000000
max,3.000000,1.000000,80.000000,8.000000,9.000000,512.329200,328.000000

In [28]:
# chance to survive (male/female)
df.groupby(df["sex"])["survived"].mean()

sex
female    0.727468
male      0.190985
Name: survived, dtype: float64

In [16]:
pd.pivot_table(df, index="sex")

,age,body,fare,parch,pclass,sibsp,survived
sex,,,,,,,
female,28.687071,166.62500,46.198097,0.633047,2.154506,0.652361,0.727468
male,30.585233,160.39823,26.154601,0.247924,2.372479,0.413998,0.190985

In [17]:
pd.pivot_table(df, index="pclass")

              age        body       fare     parch     sibsp  survived
pclass
1       39.159918  162.828571  87.508992  0.365325  0.436533  0.619195
2       29.506705  167.387097  21.179196  0.368231  0.393502  0.429603
3       24.816367  155.818182  13.302889  0.400564  0.568406  0.255289

In [18]:
pd.pivot_table(df, index="survived")

                age        body       fare     parch    pclass     sibsp
survived
0         30.545369  160.809917  23.353831  0.328801  2.500618  0.521632
1         28.918228         NaN  49.361184  0.476000  1.962000  0.462000

In [19]:
conn = sqlite3.connect(':memory:')
c = conn.cursor()

In [20]:
c.execute("""CREATE TABLE titanic (
            class integer,
            survived boolean,
            name text,
            sex text,
            age float,
            fare float
            )""")

In [21]:
# c.execute("""insert into titanic (class, survived, name, sex, age, fare) VALUES (?, ?, ?, ?, ?, ?)""",
#          (list(df["pclass"]), df["survived"], df["name"], df["sex"], df['age'], df['fare']))


c.execute("delete from titanic")
cls = list(df["pclass"])
svd = list(df["survived"])
nam = list(df["name"])
sex = list(df["sex"])
age = list(df["age"])
far = list(df["fare"])

for i in range(len(cls)):
    c.execute("""insert into titanic (class, survived, name, sex, age, fare) VALUES (?, ?, ?, ?, ?, ?)""",
        (cls[i], svd[i], nam[i], sex[i], age[i], far[i]))
    
conn.commit()
c.execute("select * from titanic").fetchall()

[(1, 1, 'Allen, Miss. Elisabeth Walton', 'female', 29.0, 211.3375),
 (1, 1, 'Allison, Master. Hudson Trevor', 'male', 0.9167, 151.55),
 (1, 0, 'Allison, Miss. Helen Loraine', 'female', 2.0, 151.55),
 (1, 0, 'Allison, Mr. Hudson Joshua Creighton', 'male', 30.0, 151.55),
 (1,
  0,
  'Allison, Mrs. Hudson J C (Bessie Waldo Daniels)',
  'female',
  25.0,
  151.55),
 (1, 1, 'Anderson, Mr. Harry', 'male', 48.0, 26.55),
 (1, 1, 'Andrews, Miss. Kornelia Theodosia', 'female', 63.0, 77.9583),
 (1, 0, 'Andrews, Mr. Thomas Jr', 'male', 39.0, 0.0),
 (1,
  1,
  'Appleton, Mrs. Edward Dale (Charlotte Lamson)',
  'female',
  53.0,
  51.4792),
 (1, 0, 'Artagaveytia, Mr. Ramon', 'male', 71.0, 49.5042),
 (1, 0, 'Astor, Col. John Jacob', 'male', 47.0, 227.525),
 (1,
  1,
  'Astor, Mrs. John Jacob (Madeleine Talmadge Force)',
  'female',
  18.0,
  227.525),
 (1, 1, 'Aubart, Mme. Leontine Pauline', 'female', 24.0, 69.3),
 (1, 1, 'Barber, Miss. Ellen "Nellie"', 'female', 26.0, 78.85),
 (1, 1, 'Barkworth, Mr. Algernon Henry Wilson', 'male', 80.0, 30.0),
 (1, 0, 'Baumann, Mr. John D', 'male', None, 25.925),
 (1, 0, 'Baxter, Mr. Quigg Edmond', 'male', 24.0, 247.5208),
 (1,
  1,
  'Baxter, Mrs. James (Helene DeLaudeniere Chaput)',
  'female',
  50.0,
  247.5208),
 (1, 1, 'Bazzani, Miss. Albina', 'female', 32.0, 76.2917),
 (1, 0, 'Beattie, Mr. Thomson', 'male', 36.0, 75.2417),
 (1, 1, 'Beckwith, Mr. Richard Leonard', 'male', 37.0, 52.5542),
 (1,
  1,
  'Beckwith, Mrs. Richard Leonard (Sallie Monypeny)',
  'female',
  47.0,
  52.5542),
 (1, 1, 'Behr, Mr. Karl Howell', 'male', 26.0, 30.0),
 (1, 1, 'Bidois, Miss. Rosalie', 'female', 42.0, 227.525),
 (1, 1, 'Bird, Miss. Ellen', 'female', 29.0, 221.7792),
 (1, 0, 'Birnbaum, Mr. Jakob', 'male', 25.0, 26.0),
 (1, 1, 'Bishop, Mr. Dickinson H', 'male', 25.0, 91.0792),
 (1, 1, 'Bishop, Mrs. Dickinson H (Helen Walton)', 'female', 19.0, 91.0792),
 (1, 1, 'Bissette, Miss. Amelia', 'female', 35.0, 135.6333),
 (1, 1, 'Bjornstrom-Steffansson, Mr. Mauritz Hakan', 'male', 28.0, 26.55),
 (1, 0, 'Blackwell, Mr. Stephen Weart', 'male', 45.0, 35.5),
 (1, 1, 'Blank, Mr. Henry', 'male', 40.0, 31.0),
 (1, 1, 'Bonnell, Miss. Caroline', 'female', 30.0, 164.8667),
 (1, 1, 'Bonnell, Miss. Elizabeth', 'female', 58.0, 26.55),
 (1, 0, 'Borebank, Mr. John James', 'male', 42.0, 26.55),
 (1, 1, 'Bowen, Miss. Grace Scott', 'female', 45.0, 262.375),
 (1, 1, 'Bowerman, Miss. Elsie Edith', 'female', 22.0, 55.0),
 (1, 1, 'Bradley, Mr. George ("George Arthur Brayton")', 'male', None, 26.55),
 (1, 0, 'Brady, Mr. John Bertram', 'male', 41.0, 30.5),
 (1, 0, 'Brandeis, Mr. Emil', 'male', 48.0, 50.4958),
 (1, 0, 'Brewe, Dr. Arthur Jackson', 'male', None, 39.6),
 (1, 1, 'Brown, Mrs. James Joseph (Margaret Tobin)', 'female', 44.0, 27.7208),
 (1,
  1,
  'Brown, Mrs. John Murray (Caroline Lane Lamson)',
  'female',
  59.0,
  51.4792),
 (1,
  1,
  'Bucknell, Mrs. William Robert (Emma Eliza Ward)',
  'female',
  60.0,
  76.2917),
 (1, 1, 'Burns, Miss. Elizabeth Margaret', 'female', 41.0, 134.5),
 (1, 0, 'Butt, Major. Archibald Willingham', 'male', 45.0, 26.55),
 (1, 0, 'Cairns, Mr. Alexander', 'male', None, 31.0),
 (1, 1, 'Calderhead, Mr. Edward Pennington', 'male', 42.0, 26.2875),
 (1,
  1,
  'Candee, Mrs. Edward (Helen Churchill Hungerford)',
  'female',
  53.0,
  27.4458),
 (1, 1, 'Cardeza, Mr. Thomas Drake Martinez', 'male', 36.0, 512.3292),
 (1,
  1,
  'Cardeza, Mrs. James Warburton Martinez (Charlotte Wardle Drake)',
  'female',
  58.0,
  512.3292),
 (1, 0, 'Carlsson, Mr. Frans Olof', 'male', 33.0, 5.0),
 (1, 0, 'Carrau, Mr. Francisco M', 'male', 28.0, 47.1),
 (1, 0, 'Carrau, Mr. Jose Pedro', 'male', 17.0, 47.1),
 (1, 1, 'Carter, Master. William Thornton II', 'male', 11.0, 120.0),
 (1, 1, 'Carter, Miss. Lucile Polk', 'female', 14.0, 120.0),
 (1, 1, 'Carter, Mr. William Ernest', 'male', 36.0, 120.0),
 (1, 1, 'Carter, Mrs. William Ernest (Lucile Polk)', 'female', 36.0, 120.0),
 (1, 0, 'Case, Mr. Howard Brown', 'male', 49.0, 26.0),
 (1,
  1,
  'Cassebeer, Mrs. Henry Arthur Jr (Eleanor Genevieve Fosdick)',
  'female',
  None,
  27.7208),
 (1, 0, 'Cavendish, Mr. Tyrell William', 'male', 36.0, 78.85),
 (1,
  1,
  'Cavendish, Mrs. Tyrell William (Julia Florence Siegel)',
  'female',
  76.0,
  78.85),
 (1, 0, 'Chaffee, Mr. Herbert Fuller', 'male', 46.0, 61.175),
 (1,
  1,
  'Chaffee, Mrs. Herbert Fuller (Carrie Constance Toogood)',
  'female',
  47.0,
  61.175),
 (1, 1, 'Chambers, Mr. Norman Campbell', 'male', 27.0, 53.1),
 (1,
  1,
  'Chambers, Mrs. Norman Campbell (Bertha Griggs)',
  'female',
  33.0,
  53.1),
 (1, 1, 'Chaudanson, Miss. Victorine', 'female', 36.0, 262.375),
 (1, 1, 'Cherry, Miss. Gladys', 'female', 30.0, 86.5),
 (1, 1, 'Chevre, Mr. Paul Romaine', 'male', 45.0, 29.7),
 (1, 1, 'Chibnall, Mrs. (Edith Martha Bowerman)', 'female', None, 55.0),
 (1, 0, 'Chisholm, Mr. Roderick Robert Crispin', 'male', None, 0.0),
 (1, 0, 'Clark, Mr. Walter Miller', 'male', 27.0, 136.7792),
 (1,
  1,
  'Clark, Mrs. Walter Miller (Virginia McDowell)',
  'female',
  26.0,
  136.7792),
 (1, 1, 'Cleaver, Miss. Alice', 'female', 22.0, 151.55),
 (1, 0, 'Clifford, Mr. George Quincy', 'male', None, 52.0),
 (1, 0, 'Colley, Mr. Edward Pomeroy', 'male', 47.0, 25.5875),
 (1, 1, 'Compton, Miss. Sara Rebecca', 'female', 39.0, 83.1583),
 (1, 0, 'Compton, Mr. Alexander Taylor Jr', 'male', 37.0, 83.1583),
 (1,
  1,
  'Compton, Mrs. Alexander Taylor (Mary Eliza Ingersoll)',
  'female',
  64.0,
  83.1583),
 (1,
  1,
  'Cornell, Mrs. Robert Clifford (Malvina Helen Lamson)',
  'female',
  55.0,
  25.7),
 (1, 0, 'Crafton, Mr. John Bertram', 'male', None, 26.55),
 (1, 0, 'Crosby, Capt. Edward Gifford', 'male', 70.0, 71.0),
 (1, 1, 'Crosby, Miss. Harriet R', 'female', 36.0, 71.0),
 (1,
  1,
  'Crosby, Mrs. Edward Gifford (Catherine Elizabeth Halstead)',
  'female',
  64.0,
  26.55),
 (1, 0, 'Cumings, Mr. John Bradley', 'male', 39.0, 71.2833),
 (1,
  1,
  'Cumings, Mrs. John Bradley (Florence Briggs Thayer)',
  'female',
  38.0,
  71.2833),
 (1, 1, 'Daly, Mr. Peter Denis ', 'male', 51.0, 26.55),
 (1, 1, 'Daniel, Mr. Robert Williams', 'male', 27.0, 30.5),
 (1, 1, 'Daniels, Miss. Sarah', 'female', 33.0, 151.55),
 (1, 0, 'Davidson, Mr. Thornton', 'male', 31.0, 52.0),
 (1, 1, 'Davidson, Mrs. Thornton (Orian Hays)', 'female', 27.0, 52.0),
 (1, 1, 'Dick, Mr. Albert Adrian', 'male', 31.0, 57.0),
 (1, 1, 'Dick, Mrs. Albert Adrian (Vera Gillespie)', 'female', 17.0, 57.0),
 (1, 1, 'Dodge, Dr. Washington', 'male', 53.0, 81.8583),
 (1, 1, 'Dodge, Master. Washington', 'male', 4.0, 81.8583),
 (1, 1, 'Dodge, Mrs. Washington (Ruth Vidaver)', 'female', 54.0, 81.8583),
 (1, 0, 'Douglas, Mr. Walter Donald', 'male', 50.0, 106.425),
 (1,
  1,
  'Douglas, Mrs. Frederick Charles (Mary Helene Baxter)',
  'female',
  27.0,
  247.5208),
 (1,
  1,
  'Douglas, Mrs. Walter Donald (Mahala Dutton)',
  'female',
  48.0,
  106.425),
 (1,
  1,
  'Duff Gordon, Lady. (Lucille Christiana Sutherland) ("Mrs Morgan")',
  'female',
  48.0,
  39.6),
 (1, 1, 'Duff Gordon, Sir. Cosmo Edmund ("Mr Morgan")', 'male', 49.0, 56.9292),
 (1, 0, 'Dulles, Mr. William Crothers', 'male', 39.0, 29.7),
 (1, 1, 'Earnshaw, Mrs. Boulton (Olive Potter)', 'female', 23.0, 83.1583),
 (1, 1, 'Endres, Miss. Caroline Louise', 'female', 38.0, 227.525),
 (1, 1, 'Eustis, Miss. Elizabeth Mussey', 'female', 54.0, 78.2667),
 (1, 0, 'Evans, Miss. Edith Corse', 'female', 36.0, 31.6792),
 (1, 0, 'Farthing, Mr. John', 'male', None, 221.7792),
 (1, 1, 'Flegenheim, Mrs. Alfred (Antoinette)', 'female', None, 31.6833),
 (1, 1, 'Fleming, Miss. Margaret', 'female', None, 110.8833),
 (1, 1, 'Flynn, Mr. John Irwin ("Irving")', 'male', 36.0, 26.3875),
 (1, 0, 'Foreman, Mr. Benjamin Laventall', 'male', 30.0, 27.75),
 (1, 1, 'Fortune, Miss. Alice Elizabeth', 'female', 24.0, 263.0),
 (1, 1, 'Fortune, Miss. Ethel Flora', 'female', 28.0, 263.0),
 (1, 1, 'Fortune, Miss. Mabel Helen', 'female', 23.0, 263.0),
 (1, 0, 'Fortune, Mr. Charles Alexander', 'male', 19.0, 263.0),
 (1, 0, 'Fortune, Mr. Mark', 'male', 64.0, 263.0),
 (1, 1, 'Fortune, Mrs. Mark (Mary McDougald)', 'female', 60.0, 263.0),
 (1, 1, 'Francatelli, Miss. Laura Mabel', 'female', 30.0, 56.9292),
 (1, 0, 'Franklin, Mr. Thomas Parham', 'male', None, 26.55),
 (1, 1, 'Frauenthal, Dr. Henry William', 'male', 50.0, 133.65),
 (1, 1, 'Frauenthal, Mr. Isaac Gerald', 'male', 43.0, 27.7208),
 (1,
  1,
  'Frauenthal, Mrs. Henry William (Clara Heinsheimer)',
  'female',
  None,
  133.65),
 (1, 1, 'Frolicher, Miss. Hedwig Margaritha', 'female', 22.0, 49.5),
 (1, 1, 'Frolicher-Stehli, Mr. Maxmillian', 'male', 60.0, 79.2),
 (1,
  1,
  'Frolicher-Stehli, Mrs. Maxmillian (Margaretha Emerentia Stehli)',
  'female',
  48.0,
  79.2),
 (1, 0, 'Fry, Mr. Richard', 'male', None, 0.0),
 (1, 0, 'Futrelle, Mr. Jacques Heath', 'male', 37.0, 53.1),
 (1, 1, 'Futrelle, Mrs. Jacques Heath (Lily May Peel)', 'female', 35.0, 53.1),
 (1, 0, 'Gee, Mr. Arthur H', 'male', 47.0, 38.5),
 (1, 1, 'Geiger, Miss. Amalie', 'female', 35.0, 211.5),
 (1, 1, 'Gibson, Miss. Dorothy Winifred', 'female', 22.0, 59.4),
 (1, 1, 'Gibson, Mrs. Leonard (Pauline C Boeson)', 'female', 45.0, 59.4),
 (1, 0, 'Giglio, Mr. Victor', 'male', 24.0, 79.2),
 (1, 1, 'Goldenberg, Mr. Samuel L', 'male', 49.0, 89.1042),
 (1,
  1,
  'Goldenberg, Mrs. Samuel L (Edwiga Grabowska)',
  'female',
  None,
  89.1042),
 (1, 0, 'Goldschmidt, Mr. George B', 'male', 71.0, 34.6542),
 (1, 1, 'Gracie, Col. Archibald IV', 'male', 53.0, 28.5),
 (1, 1, 'Graham, Miss. Margaret Edith', 'female', 19.0, 30.0),
 (1, 0, 'Graham, Mr. George Edward', 'male', 38.0, 153.4625),
 (1,
  1,
  'Graham, Mrs. William Thompson (Edith Junkins)',
  'female',
  58.0,
  153.4625),
 (1, 1, 'Greenfield, Mr. William Bertram', 'male', 23.0, 63.3583),
 (1,
  1,
  'Greenfield, Mrs. Leo David (Blanche Strouse)',
  'female',
  45.0,
  63.3583),
 (1, 0, 'Guggenheim, Mr. Benjamin', 'male', 46.0, 79.2),
 (1, 1, 'Harder, Mr. George Achilles', 'male', 25.0, 55.4417),
 (1,
  1,
  'Harder, Mrs. George Achilles (Dorothy Annan)',
  'female',
  25.0,
  55.4417),
 (1, 1, 'Harper, Mr. Henry Sleeper', 'male', 48.0, 76.7292),
 (1, 1, 'Harper, Mrs. Henry Sleeper (Myna Haxtun)', 'female', 49.0, 76.7292),
 (1, 0, 'Harrington, Mr. Charles H', 'male', None, 42.4),
 (1, 0, 'Harris, Mr. Henry Birkhardt', 'male', 45.0, 83.475),
 (1,
  1,
  'Harris, Mrs. Henry Birkhardt (Irene Wallach)',
  'female',
  35.0,
  83.475),
 (1, 0, 'Harrison, Mr. William', 'male', 40.0, 0.0),
 (1, 1, 'Hassab, Mr. Hammad', 'male', 27.0, 76.7292),
 (1, 1, 'Hawksford, Mr. Walter James', 'male', None, 30.0),
 (1, 1, 'Hays, Miss. Margaret Bechstein', 'female', 24.0, 83.1583),
 (1, 0, 'Hays, Mr. Charles Melville', 'male', 55.0, 93.5),
 (1,
  1,
  'Hays, Mrs. Charles Melville (Clara Jennings Gregg)',
  'female',
  52.0,
  93.5),
 (1, 0, 'Head, Mr. Christopher', 'male', 42.0, 42.5),
 (1, 0, 'Hilliard, Mr. Herbert Henry', 'male', None, 51.8625),
 (1, 0, 'Hipkins, Mr. William Edward', 'male', 55.0, 50.0),
 (1, 1, 'Hippach, Miss. Jean Gertrude', 'female', 16.0, 57.9792),
 (1,
  1,
  'Hippach, Mrs. Louis Albert (Ida Sophia Fischer)',
  'female',
  44.0,
  57.9792),
 (1, 1, 'Hogeboom, Mrs. John C (Anna Andrews)', 'female', 51.0, 77.9583),
 (1, 0, 'Holverson, Mr. Alexander Oskar', 'male', 42.0, 52.0),
 (1,
  1,
  'Holverson, Mrs. Alexander Oskar (Mary Aline Towner)',
  'female',
  35.0,
  52.0),
 (1, 1, 'Homer, Mr. Harry ("Mr E Haven")', 'male', 35.0, 26.55),
 (1, 1, 'Hoyt, Mr. Frederick Maxfield', 'male', 38.0, 90.0),
 (1, 0, 'Hoyt, Mr. William Fisher', 'male', None, 30.6958),
 (1,
  1,
  'Hoyt, Mrs. Frederick Maxfield (Jane Anne Forby)',
  'female',
  35.0,
  90.0),
 (1, 1, 'Icard, Miss. Amelie', 'female', 38.0, 80.0),
 (1, 0, 'Isham, Miss. Ann Elizabeth', 'female', 50.0, 28.7125),
 (1, 1, 'Ismay, Mr. Joseph Bruce', 'male', 49.0, 0.0),
 (1, 0, 'Jones, Mr. Charles Cresson', 'male', 46.0, 26.0),
 (1, 0, 'Julian, Mr. Henry Forbes', 'male', 50.0, 26.0),
 (1, 0, 'Keeping, Mr. Edwin', 'male', 32.5, 211.5),
 (1, 0, 'Kent, Mr. Edward Austin', 'male', 58.0, 29.7),
 (1, 0, 'Kenyon, Mr. Frederick R', 'male', 41.0, 51.8625),
 (1, 1, 'Kenyon, Mrs. Frederick R (Marion)', 'female', None, 51.8625),
 (1, 1, 'Kimball, Mr. Edwin Nelson Jr', 'male', 42.0, 52.5542),
 (1,
  1,
  'Kimball, Mrs. Edwin Nelson Jr (Gertrude Parsons)',
  'female',
  45.0,
  52.5542),
 (1, 0, 'Klaber, Mr. Herman', 'male', None, 26.55),
 (1, 1, 'Kreuchen, Miss. Emilie', 'female', 39.0, 211.3375),
 (1, 1, 'Leader, Dr. Alice (Farnham)', 'female', 49.0, 25.9292),
 (1, 1, 'LeRoy, Miss. Bertha', 'female', 30.0, 106.425),
 (1, 1, 'Lesurer, Mr. Gustave J', 'male', 35.0, 512.3292),
 (1, 0, 'Lewy, Mr. Ervin G', 'male', None, 27.7208),
 (1,
  0,
  'Lindeberg-Lind, Mr. Erik Gustaf ("Mr Edward Lingrey")',
  'male',
  42.0,
  26.55),
 (1, 1, 'Lindstrom, Mrs. Carl Johan (Sigrid Posse)', 'female', 55.0, 27.7208),
 (1, 1, 'Lines, Miss. Mary Conover', 'female', 16.0, 39.4),
 (1,
  1,
  'Lines, Mrs. Ernest H (Elizabeth Lindsey James)',
  'female',
  51.0,
  39.4),
 (1, 0, 'Long, Mr. Milton Clyde', 'male', 29.0, 30.0),
 (1, 1, 'Longley, Miss. Gretchen Fiske', 'female', 21.0, 77.9583),
 (1, 0, 'Loring, Mr. Joseph Holland', 'male', 30.0, 45.5),
 (1, 1, 'Lurette, Miss. Elise', 'female', 58.0, 146.5208),
 (1, 1, 'Madill, Miss. Georgette Alexandra', 'female', 15.0, 211.3375),
 (1, 0, 'Maguire, Mr. John Edward', 'male', 30.0, 26.0),
 (1, 1, 'Maioni, Miss. Roberta', 'female', 16.0, 86.5),
 (1, 1, 'Marechal, Mr. Pierre', 'male', None, 29.7),
 (1, 0, 'Marvin, Mr. Daniel Warner', 'male', 19.0, 53.1),
 (1,
  1,
  'Marvin, Mrs. Daniel Warner (Mary Graham Carmichael Farquarson)',
  'female',
  18.0,
  53.1),
 (1,
  1,
  'Mayne, Mlle. Berthe Antonine ("Mrs de Villiers")',
  'female',
  24.0,
  49.5042),
 (1, 0, 'McCaffry, Mr. Thomas Francis', 'male', 46.0, 75.2417),
 (1, 0, 'McCarthy, Mr. Timothy J', 'male', 54.0, 51.8625),
 (1, 1, 'McGough, Mr. James Robert', 'male', 36.0, 26.2875),
 (1, 0, 'Meyer, Mr. Edgar Joseph', 'male', 28.0, 82.1708),
 (1, 1, 'Meyer, Mrs. Edgar Joseph (Leila Saks)', 'female', None, 82.1708),
 (1, 0, 'Millet, Mr. Francis Davis', 'male', 65.0, 26.55),
 (1, 0, 'Minahan, Dr. William Edward', 'male', 44.0, 90.0),
 (1, 1, 'Minahan, Miss. Daisy E', 'female', 33.0, 90.0),
 (1,
  1,
  'Minahan, Mrs. William Edward (Lillian E Thorpe)',
  'female',
  37.0,
  90.0),
 (1, 1, 'Mock, Mr. Philipp Edmund', 'male', 30.0, 57.75),
 (1, 0, 'Molson, Mr. Harry Markland', 'male', 55.0, 30.5),
 (1, 0, 'Moore, Mr. Clarence Bloomfield', 'male', 47.0, 42.4),
 (1, 0, 'Natsch, Mr. Charles H', 'male', 37.0, 29.7),
 (1, 1, 'Newell, Miss. Madeleine', 'female', 31.0, 113.275),
 (1, 1, 'Newell, Miss. Marjorie', 'female', 23.0, 113.275),
 (1, 0, 'Newell, Mr. Arthur Webster', 'male', 58.0, 113.275),
 (1, 1, 'Newsom, Miss. Helen Monypeny', 'female', 19.0, 26.2833),
 (1, 0, 'Nicholson, Mr. Arthur Ernest', 'male', 64.0, 26.0),
 (1, 1, 'Oliva y Ocana, Dona. Fermina', 'female', 39.0, 108.9),
 (1, 1, 'Omont, Mr. Alfred Fernand', 'male', None, 25.7417),
 (1, 1, 'Ostby, Miss. Helene Ragnhild', 'female', 22.0, 61.9792),
 (1, 0, 'Ostby, Mr. Engelhart Cornelius', 'male', 65.0, 61.9792),
 (1, 0, 'Ovies y Rodriguez, Mr. Servando', 'male', 28.5, 27.7208),
 (1, 0, 'Parr, Mr. William Henry Marsh', 'male', None, 0.0),
 (1, 0, 'Partner, Mr. Austen', 'male', 45.5, 28.5),
 (1, 0, 'Payne, Mr. Vivian Ponsonby', 'male', 23.0, 93.5),
 (1, 0, 'Pears, Mr. Thomas Clinton', 'male', 29.0, 66.6),
 (1, 1, 'Pears, Mrs. Thomas (Edith Wearne)', 'female', 22.0, 66.6),
 (1, 0, 'Penasco y Castellana, Mr. Victor de Satode', 'male', 18.0, 108.9),
 (1,
  1,
  'Penasco y Castellana, Mrs. Victor de Satode (Maria Josefa Perez de Soto y Vallejo)',
  'female',
  17.0,
  108.9),
 (1, 1, 'Perreault, Miss. Anne', 'female', 30.0, 93.5),
 (1, 1, 'Peuchen, Major. Arthur Godfrey', 'male', 52.0, 30.5),
 (1, 0, 'Porter, Mr. Walter Chamberlain', 'male', 47.0, 52.0),
 (1,
  1,
  'Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)',
  'female',
  56.0,
  83.1583),
 (1, 0, 'Reuchlin, Jonkheer. John George', 'male', 38.0, 0.0),
 (1, 1, 'Rheims, Mr. George Alexander Lucien', 'male', None, 39.6),
 (1, 0, 'Ringhini, Mr. Sante', 'male', 22.0, 135.6333),
 (1, 0, 'Robbins, Mr. Victor', 'male', None, 227.525),
 (1,
  1,
  'Robert, Mrs. Edward Scott (Elisabeth Walton McMillan)',
  'female',
  43.0,
  211.3375),
 (1, 0, 'Roebling, Mr. Washington Augustus II', 'male', 31.0, 50.4958),
 (1, 1, 'Romaine, Mr. Charles Hallace ("Mr C Rolmane")', 'male', 45.0, 26.55),
 (1, 0, 'Rood, Mr. Hugh Roscoe', 'male', None, 50.0),
 (1, 1, 'Rosenbaum, Miss. Edith Louise', 'female', 33.0, 27.7208),
 (1, 0, 'Rosenshine, Mr. George ("Mr George Thorne")', 'male', 46.0, 79.2),
 (1, 0, 'Ross, Mr. John Hugo', 'male', 36.0, 40.125),
 (1,
  1,
  'Rothes, the Countess. of (Lucy Noel Martha Dyer-Edwards)',
  'female',
  33.0,
  86.5),
 (1, 0, 'Rothschild, Mr. Martin', 'male', 55.0, 59.4),
 (1,
  1,
  'Rothschild, Mrs. Martin (Elizabeth L. Barrett)',
  'female',
  54.0,
  59.4),
 (1, 0, 'Rowe, Mr. Alfred G', 'male', 33.0, 26.55),
 (1, 1, 'Ryerson, Master. John Borie', 'male', 13.0, 262.375),
 (1, 1, 'Ryerson, Miss. Emily Borie', 'female', 18.0, 262.375),
 (1, 1, 'Ryerson, Miss. Susan Parker "Suzette"', 'female', 21.0, 262.375),
 (1, 0, 'Ryerson, Mr. Arthur Larned', 'male', 61.0, 262.375),
 (1,
  1,
  'Ryerson, Mrs. Arthur Larned (Emily Maria Borie)',
  'female',
  48.0,
  262.375),
 (1, 1, 'Saalfeld, Mr. Adolphe', 'male', None, 30.5),
 (1, 1, 'Sagesser, Mlle. Emma', 'female', 24.0, 69.3),
 (1, 1, 'Salomon, Mr. Abraham L', 'male', None, 26.0),
 (1, 1, 'Schabert, Mrs. Paul (Emma Mock)', 'female', 35.0, 57.75),
 (1, 1, 'Serepeca, Miss. Augusta', 'female', 30.0, 31.0),
 (1, 1, 'Seward, Mr. Frederic Kimber', 'male', 34.0, 26.55),
 (1, 1, 'Shutes, Miss. Elizabeth W', 'female', 40.0, 153.4625),
 (1, 1, 'Silverthorne, Mr. Spencer Victor', 'male', 35.0, 26.2875),
 (1, 0, 'Silvey, Mr. William Baird', 'male', 50.0, 55.9),
 (1, 1, 'Silvey, Mrs. William Baird (Alice Munger)', 'female', 39.0, 55.9),
 (1, 1, 'Simonius-Blumer, Col. Oberst Alfons', 'male', 56.0, 35.5),
 (1, 1, 'Sloper, Mr. William Thompson', 'male', 28.0, 35.5),
 (1, 0, 'Smart, Mr. John Montgomery', 'male', 56.0, 26.55),
 (1, 0, 'Smith, Mr. James Clinch', 'male', 56.0, 30.6958),
 (1, 0, 'Smith, Mr. Lucien Philip', 'male', 24.0, 60.0),
 (1, 0, 'Smith, Mr. Richard William', 'male', None, 26.0),
 (1,
  1,
  'Smith, Mrs. Lucien Philip (Mary Eloise Hughes)',
  'female',
  18.0,
  60.0),
 (1, 1, 'Snyder, Mr. John Pillsbury', 'male', 24.0, 82.2667),
 (1,
  1,
  'Snyder, Mrs. John Pillsbury (Nelle Stevenson)',
  'female',
  23.0,
  82.2667),
 (1, 1, 'Spedden, Master. Robert Douglas', 'male', 6.0, 134.5),
 (1, 1, 'Spedden, Mr. Frederic Oakley', 'male', 45.0, 134.5),
 (1,
  1,
  'Spedden, Mrs. Frederic Oakley (Margaretta Corning Stone)',
  'female',
  40.0,
  134.5),
 (1, 0, 'Spencer, Mr. William Augustus', 'male', 57.0, 146.5208),
 (1,
  1,
  'Spencer, Mrs. William Augustus (Marie Eugenie)',
  'female',
  None,
  146.5208),
 (1, 1, 'Stahelin-Maeglin, Dr. Max', 'male', 32.0, 30.5),
 (1, 0, 'Stead, Mr. William Thomas', 'male', 62.0, 26.55),
 (1, 1, 'Stengel, Mr. Charles Emil Henry', 'male', 54.0, 55.4417),
 (1,
  1,
  'Stengel, Mrs. Charles Emil Henry (Annie May Morris)',
  'female',
  43.0,
  55.4417),
 (1,
  1,
  'Stephenson, Mrs. Walter Bertram (Martha Eustis)',
  'female',
  52.0,
  78.2667),
 (1, 0, 'Stewart, Mr. Albert A', 'male', None, 27.7208),
 (1, 1, 'Stone, Mrs. George Nelson (Martha Evelyn)', 'female', 62.0, 80.0),
 (1, 0, 'Straus, Mr. Isidor', 'male', 67.0, 221.7792),
 (1, 0, 'Straus, Mrs. Isidor (Rosalie Ida Blun)', 'female', 63.0, 221.7792),
 (1, 0, 'Sutton, Mr. Frederick', 'male', 61.0, 32.3208),
 (1,
  1,
  'Swift, Mrs. Frederick Joel (Margaret Welles Barron)',
  'female',
  48.0,
  25.9292),
 (1, 1, 'Taussig, Miss. Ruth', 'female', 18.0, 79.65),
 (1, 0, 'Taussig, Mr. Emil', 'male', 52.0, 79.65),
 (1, 1, 'Taussig, Mrs. Emil (Tillie Mandelbaum)', 'female', 39.0, 79.65),

In [22]:
c.execute("delete from titanic")

for i in range(len(df)):
    c.execute("""insert into titanic (class, survived, name, sex, age, fare) VALUES (?, ?, ?, ?, ?, ?)""",
        (int(df["pclass"][i]), bool(df["survived"][i]), df["name"][i], df["sex"][i], df["age"][i], df["fare"][i]))
    
conn.commit()
c.execute("select * from titanic").fetchall()

[(1, 1, 'Allen, Miss. Elisabeth Walton', 'female', 29.0, 211.3375),
 (1, 1, 'Allison, Master. Hudson Trevor', 'male', 0.9167, 151.55),
 (1, 0, 'Allison, Miss. Helen Loraine', 'female', 2.0, 151.55),
 (1, 0, 'Allison, Mr. Hudson Joshua Creighton', 'male', 30.0, 151.55),
 (1,
  0,
  'Allison, Mrs. Hudson J C (Bessie Waldo Daniels)',
  'female',
  25.0,
  151.55),
 (1, 1, 'Anderson, Mr. Harry', 'male', 48.0, 26.55),
 (1, 1, 'Andrews, Miss. Kornelia Theodosia', 'female', 63.0, 77.9583),
 (1, 0, 'Andrews, Mr. Thomas Jr', 'male', 39.0, 0.0),
 (1,
  1,
  'Appleton, Mrs. Edward Dale (Charlotte Lamson)',
  'female',
  53.0,
  51.4792),
 (1, 0, 'Artagaveytia, Mr. Ramon', 'male', 71.0, 49.5042),
 (1, 0, 'Astor, Col. John Jacob', 'male', 47.0, 227.525),
 (1,
  1,
  'Astor, Mrs. John Jacob (Madeleine Talmadge Force)',
  'female',
  18.0,
  227.525),
 (1, 1, 'Aubart, Mme. Leontine Pauline', 'female', 24.0, 69.3),
 (1, 1, 'Barber, Miss. Ellen "Nellie"', 'female', 26.0, 78.85),
 (1, 1, 'Barkworth, Mr. Algernon Henry Wilson', 'male', 80.0, 30.0),
 (1, 0, 'Baumann, Mr. John D', 'male', None, 25.925),
 (1, 0, 'Baxter, Mr. Quigg Edmond', 'male', 24.0, 247.5208),
 (1,
  1,
  'Baxter, Mrs. James (Helene DeLaudeniere Chaput)',
  'female',
  50.0,
  247.5208),
 (1, 1, 'Bazzani, Miss. Albina', 'female', 32.0, 76.2917),
 (1, 0, 'Beattie, Mr. Thomson', 'male', 36.0, 75.2417),
 (1, 1, 'Beckwith, Mr. Richard Leonard', 'male', 37.0, 52.5542),
 (1,
  1,
  'Beckwith, Mrs. Richard Leonard (Sallie Monypeny)',
  'female',
  47.0,
  52.5542),
 (1, 1, 'Behr, Mr. Karl Howell', 'male', 26.0, 30.0),
 (1, 1, 'Bidois, Miss. Rosalie', 'female', 42.0, 227.525),
 (1, 1, 'Bird, Miss. Ellen', 'female', 29.0, 221.7792),
 (1, 0, 'Birnbaum, Mr. Jakob', 'male', 25.0, 26.0),
 (1, 1, 'Bishop, Mr. Dickinson H', 'male', 25.0, 91.0792),
 (1, 1, 'Bishop, Mrs. Dickinson H (Helen Walton)', 'female', 19.0, 91.0792),
 (1, 1, 'Bissette, Miss. Amelia', 'female', 35.0, 135.6333),
 (1, 1, 'Bjornstrom-Steffansson, Mr. Mauritz Hakan', 'male', 28.0, 26.55),
 (1, 0, 'Blackwell, Mr. Stephen Weart', 'male', 45.0, 35.5),
 (1, 1, 'Blank, Mr. Henry', 'male', 40.0, 31.0),
 (1, 1, 'Bonnell, Miss. Caroline', 'female', 30.0, 164.8667),
 (1, 1, 'Bonnell, Miss. Elizabeth', 'female', 58.0, 26.55),
 (1, 0, 'Borebank, Mr. John James', 'male', 42.0, 26.55),
 (1, 1, 'Bowen, Miss. Grace Scott', 'female', 45.0, 262.375),
 (1, 1, 'Bowerman, Miss. Elsie Edith', 'female', 22.0, 55.0),
 (1, 1, 'Bradley, Mr. George ("George Arthur Brayton")', 'male', None, 26.55),
 (1, 0, 'Brady, Mr. John Bertram', 'male', 41.0, 30.5),
 (1, 0, 'Brandeis, Mr. Emil', 'male', 48.0, 50.4958),
 (1, 0, 'Brewe, Dr. Arthur Jackson', 'male', None, 39.6),
 (1, 1, 'Brown, Mrs. James Joseph (Margaret Tobin)', 'female', 44.0, 27.7208),
 (1,
  1,
  'Brown, Mrs. John Murray (Caroline Lane Lamson)',
  'female',
  59.0,
  51.4792),
 (1,
  1,
  'Bucknell, Mrs. William Robert (Emma Eliza Ward)',
  'female',
  60.0,
  76.2917),
 (1, 1, 'Burns, Miss. Elizabeth Margaret', 'female', 41.0, 134.5),
 (1, 0, 'Butt, Major. Archibald Willingham', 'male', 45.0, 26.55),
 (1, 0, 'Cairns, Mr. Alexander', 'male', None, 31.0),
 (1, 1, 'Calderhead, Mr. Edward Pennington', 'male', 42.0, 26.2875),
 (1,
  1,
  'Candee, Mrs. Edward (Helen Churchill Hungerford)',
  'female',
  53.0,
  27.4458),
 (1, 1, 'Cardeza, Mr. Thomas Drake Martinez', 'male', 36.0, 512.3292),
 (1,
  1,
  'Cardeza, Mrs. James Warburton Martinez (Charlotte Wardle Drake)',
  'female',
  58.0,
  512.3292),
 (1, 0, 'Carlsson, Mr. Frans Olof', 'male', 33.0, 5.0),
 (1, 0, 'Carrau, Mr. Francisco M', 'male', 28.0, 47.1),
 (1, 0, 'Carrau, Mr. Jose Pedro', 'male', 17.0, 47.1),
 (1, 1, 'Carter, Master. William Thornton II', 'male', 11.0, 120.0),
 (1, 1, 'Carter, Miss. Lucile Polk', 'female', 14.0, 120.0),
 (1, 1, 'Carter, Mr. William Ernest', 'male', 36.0, 120.0),
 (1, 1, 'Carter, Mrs. William Ernest (Lucile Polk)', 'female', 36.0, 120.0),
 (1, 0, 'Case, Mr. Howard Brown', 'male', 49.0, 26.0),
 (1,
  1,
  'Cassebeer, Mrs. Henry Arthur Jr (Eleanor Genevieve Fosdick)',
  'female',
  None,
  27.7208),
 (1, 0, 'Cavendish, Mr. Tyrell William', 'male', 36.0, 78.85),
 (1,
  1,
  'Cavendish, Mrs. Tyrell William (Julia Florence Siegel)',
  'female',
  76.0,
  78.85),
 (1, 0, 'Chaffee, Mr. Herbert Fuller', 'male', 46.0, 61.175),
 (1,
  1,
  'Chaffee, Mrs. Herbert Fuller (Carrie Constance Toogood)',
  'female',
  47.0,
  61.175),
 (1, 1, 'Chambers, Mr. Norman Campbell', 'male', 27.0, 53.1),
 (1,
  1,
  'Chambers, Mrs. Norman Campbell (Bertha Griggs)',
  'female',
  33.0,
  53.1),
 (1, 1, 'Chaudanson, Miss. Victorine', 'female', 36.0, 262.375),
 (1, 1, 'Cherry, Miss. Gladys', 'female', 30.0, 86.5),
 (1, 1, 'Chevre, Mr. Paul Romaine', 'male', 45.0, 29.7),
 (1, 1, 'Chibnall, Mrs. (Edith Martha Bowerman)', 'female', None, 55.0),
 (1, 0, 'Chisholm, Mr. Roderick Robert Crispin', 'male', None, 0.0),
 (1, 0, 'Clark, Mr. Walter Miller', 'male', 27.0, 136.7792),
 (1,
  1,
  'Clark, Mrs. Walter Miller (Virginia McDowell)',
  'female',
  26.0,
  136.7792),
 (1, 1, 'Cleaver, Miss. Alice', 'female', 22.0, 151.55),
 (1, 0, 'Clifford, Mr. George Quincy', 'male', None, 52.0),
 (1, 0, 'Colley, Mr. Edward Pomeroy', 'male', 47.0, 25.5875),
 (1, 1, 'Compton, Miss. Sara Rebecca', 'female', 39.0, 83.1583),
 (1, 0, 'Compton, Mr. Alexander Taylor Jr', 'male', 37.0, 83.1583),
 (1,
  1,
  'Compton, Mrs. Alexander Taylor (Mary Eliza Ingersoll)',
  'female',
  64.0,
  83.1583),
 (1,
  1,
  'Cornell, Mrs. Robert Clifford (Malvina Helen Lamson)',
  'female',
  55.0,
  25.7),
 (1, 0, 'Crafton, Mr. John Bertram', 'male', None, 26.55),
 (1, 0, 'Crosby, Capt. Edward Gifford', 'male', 70.0, 71.0),
 (1, 1, 'Crosby, Miss. Harriet R', 'female', 36.0, 71.0),
 (1,
  1,
  'Crosby, Mrs. Edward Gifford (Catherine Elizabeth Halstead)',
  'female',
  64.0,
  26.55),
 (1, 0, 'Cumings, Mr. John Bradley', 'male', 39.0, 71.2833),
 (1,
  1,
  'Cumings, Mrs. John Bradley (Florence Briggs Thayer)',
  'female',
  38.0,
  71.2833),
 (1, 1, 'Daly, Mr. Peter Denis ', 'male', 51.0, 26.55),
 (1, 1, 'Daniel, Mr. Robert Williams', 'male', 27.0, 30.5),
 (1, 1, 'Daniels, Miss. Sarah', 'female', 33.0, 151.55),
 (1, 0, 'Davidson, Mr. Thornton', 'male', 31.0, 52.0),
 (1, 1, 'Davidson, Mrs. Thornton (Orian Hays)', 'female', 27.0, 52.0),
 (1, 1, 'Dick, Mr. Albert Adrian', 'male', 31.0, 57.0),
 (1, 1, 'Dick, Mrs. Albert Adrian (Vera Gillespie)', 'female', 17.0, 57.0),
 (1, 1, 'Dodge, Dr. Washington', 'male', 53.0, 81.8583),
 (1, 1, 'Dodge, Master. Washington', 'male', 4.0, 81.8583),
 (1, 1, 'Dodge, Mrs. Washington (Ruth Vidaver)', 'female', 54.0, 81.8583),
 (1, 0, 'Douglas, Mr. Walter Donald', 'male', 50.0, 106.425),
 (1,
  1,
  'Douglas, Mrs. Frederick Charles (Mary Helene Baxter)',
  'female',
  27.0,
  247.5208),
 (1,
  1,
  'Douglas, Mrs. Walter Donald (Mahala Dutton)',
  'female',
  48.0,
  106.425),
 (1,
  1,
  'Duff Gordon, Lady. (Lucille Christiana Sutherland) ("Mrs Morgan")',
  'female',
  48.0,
  39.6),
 (1, 1, 'Duff Gordon, Sir. Cosmo Edmund ("Mr Morgan")', 'male', 49.0, 56.9292),
 (1, 0, 'Dulles, Mr. William Crothers', 'male', 39.0, 29.7),
 (1, 1, 'Earnshaw, Mrs. Boulton (Olive Potter)', 'female', 23.0, 83.1583),
 (1, 1, 'Endres, Miss. Caroline Louise', 'female', 38.0, 227.525),
 (1, 1, 'Eustis, Miss. Elizabeth Mussey', 'female', 54.0, 78.2667),
 (1, 0, 'Evans, Miss. Edith Corse', 'female', 36.0, 31.6792),
 (1, 0, 'Farthing, Mr. John', 'male', None, 221.7792),
 (1, 1, 'Flegenheim, Mrs. Alfred (Antoinette)', 'female', None, 31.6833),
 (1, 1, 'Fleming, Miss. Margaret', 'female', None, 110.8833),
 (1, 1, 'Flynn, Mr. John Irwin ("Irving")', 'male', 36.0, 26.3875),
 (1, 0, 'Foreman, Mr. Benjamin Laventall', 'male', 30.0, 27.75),
 (1, 1, 'Fortune, Miss. Alice Elizabeth', 'female', 24.0, 263.0),
 (1, 1, 'Fortune, Miss. Ethel Flora', 'female', 28.0, 263.0),
 (1, 1, 'Fortune, Miss. Mabel Helen', 'female', 23.0, 263.0),
 (1, 0, 'Fortune, Mr. Charles Alexander', 'male', 19.0, 263.0),
 (1, 0, 'Fortune, Mr. Mark', 'male', 64.0, 263.0),
 (1, 1, 'Fortune, Mrs. Mark (Mary McDougald)', 'female', 60.0, 263.0),
 (1, 1, 'Francatelli, Miss. Laura Mabel', 'female', 30.0, 56.9292),
 (1, 0, 'Franklin, Mr. Thomas Parham', 'male', None, 26.55),
 (1, 1, 'Frauenthal, Dr. Henry William', 'male', 50.0, 133.65),
 (1, 1, 'Frauenthal, Mr. Isaac Gerald', 'male', 43.0, 27.7208),
 (1,
  1,
  'Frauenthal, Mrs. Henry William (Clara Heinsheimer)',
  'female',
  None,
  133.65),
 (1, 1, 'Frolicher, Miss. Hedwig Margaritha', 'female', 22.0, 49.5),
 (1, 1, 'Frolicher-Stehli, Mr. Maxmillian', 'male', 60.0, 79.2),
 (1,
  1,
  'Frolicher-Stehli, Mrs. Maxmillian (Margaretha Emerentia Stehli)',
  'female',
  48.0,
  79.2),
 (1, 0, 'Fry, Mr. Richard', 'male', None, 0.0),
 (1, 0, 'Futrelle, Mr. Jacques Heath', 'male', 37.0, 53.1),
 (1, 1, 'Futrelle, Mrs. Jacques Heath (Lily May Peel)', 'female', 35.0, 53.1),
 (1, 0, 'Gee, Mr. Arthur H', 'male', 47.0, 38.5),
 (1, 1, 'Geiger, Miss. Amalie', 'female', 35.0, 211.5),
 (1, 1, 'Gibson, Miss. Dorothy Winifred', 'female', 22.0, 59.4),
 (1, 1, 'Gibson, Mrs. Leonard (Pauline C Boeson)', 'female', 45.0, 59.4),
 (1, 0, 'Giglio, Mr. Victor', 'male', 24.0, 79.2),
 (1, 1, 'Goldenberg, Mr. Samuel L', 'male', 49.0, 89.1042),
 (1,
  1,
  'Goldenberg, Mrs. Samuel L (Edwiga Grabowska)',
  'female',
  None,
  89.1042),
 (1, 0, 'Goldschmidt, Mr. George B', 'male', 71.0, 34.6542),
 (1, 1, 'Gracie, Col. Archibald IV', 'male', 53.0, 28.5),
 (1, 1, 'Graham, Miss. Margaret Edith', 'female', 19.0, 30.0),
 (1, 0, 'Graham, Mr. George Edward', 'male', 38.0, 153.4625),
 (1,
  1,
  'Graham, Mrs. William Thompson (Edith Junkins)',
  'female',
  58.0,
  153.4625),
 (1, 1, 'Greenfield, Mr. William Bertram', 'male', 23.0, 63.3583),
 (1,
  1,
  'Greenfield, Mrs. Leo David (Blanche Strouse)',
  'female',
  45.0,
  63.3583),
 (1, 0, 'Guggenheim, Mr. Benjamin', 'male', 46.0, 79.2),
 (1, 1, 'Harder, Mr. George Achilles', 'male', 25.0, 55.4417),
 (1,
  1,
  'Harder, Mrs. George Achilles (Dorothy Annan)',
  'female',
  25.0,
  55.4417),
 (1, 1, 'Harper, Mr. Henry Sleeper', 'male', 48.0, 76.7292),
 (1, 1, 'Harper, Mrs. Henry Sleeper (Myna Haxtun)', 'female', 49.0, 76.7292),
 (1, 0, 'Harrington, Mr. Charles H', 'male', None, 42.4),
 (1, 0, 'Harris, Mr. Henry Birkhardt', 'male', 45.0, 83.475),
 (1,
  1,
  'Harris, Mrs. Henry Birkhardt (Irene Wallach)',
  'female',
  35.0,
  83.475),
 (1, 0, 'Harrison, Mr. William', 'male', 40.0, 0.0),
 (1, 1, 'Hassab, Mr. Hammad', 'male', 27.0, 76.7292),
 (1, 1, 'Hawksford, Mr. Walter James', 'male', None, 30.0),
 (1, 1, 'Hays, Miss. Margaret Bechstein', 'female', 24.0, 83.1583),
 (1, 0, 'Hays, Mr. Charles Melville', 'male', 55.0, 93.5),
 (1,
  1,
  'Hays, Mrs. Charles Melville (Clara Jennings Gregg)',
  'female',
  52.0,
  93.5),
 (1, 0, 'Head, Mr. Christopher', 'male', 42.0, 42.5),
 (1, 0, 'Hilliard, Mr. Herbert Henry', 'male', None, 51.8625),
 (1, 0, 'Hipkins, Mr. William Edward', 'male', 55.0, 50.0),
 (1, 1, 'Hippach, Miss. Jean Gertrude', 'female', 16.0, 57.9792),
 (1,
  1,
  'Hippach, Mrs. Louis Albert (Ida Sophia Fischer)',
  'female',
  44.0,
  57.9792),
 (1, 1, 'Hogeboom, Mrs. John C (Anna Andrews)', 'female', 51.0, 77.9583),
 (1, 0, 'Holverson, Mr. Alexander Oskar', 'male', 42.0, 52.0),
 (1,
  1,
  'Holverson, Mrs. Alexander Oskar (Mary Aline Towner)',
  'female',
  35.0,
  52.0),
 (1, 1, 'Homer, Mr. Harry ("Mr E Haven")', 'male', 35.0, 26.55),
 (1, 1, 'Hoyt, Mr. Frederick Maxfield', 'male', 38.0, 90.0),
 (1, 0, 'Hoyt, Mr. William Fisher', 'male', None, 30.6958),
 (1,
  1,
  'Hoyt, Mrs. Frederick Maxfield (Jane Anne Forby)',
  'female',
  35.0,
  90.0),
 (1, 1, 'Icard, Miss. Amelie', 'female', 38.0, 80.0),
 (1, 0, 'Isham, Miss. Ann Elizabeth', 'female', 50.0, 28.7125),
 (1, 1, 'Ismay, Mr. Joseph Bruce', 'male', 49.0, 0.0),
 (1, 0, 'Jones, Mr. Charles Cresson', 'male', 46.0, 26.0),
 (1, 0, 'Julian, Mr. Henry Forbes', 'male', 50.0, 26.0),
 (1, 0, 'Keeping, Mr. Edwin', 'male', 32.5, 211.5),
 (1, 0, 'Kent, Mr. Edward Austin', 'male', 58.0, 29.7),
 (1, 0, 'Kenyon, Mr. Frederick R', 'male', 41.0, 51.8625),
 (1, 1, 'Kenyon, Mrs. Frederick R (Marion)', 'female', None, 51.8625),
 (1, 1, 'Kimball, Mr. Edwin Nelson Jr', 'male', 42.0, 52.5542),
 (1,
  1,
  'Kimball, Mrs. Edwin Nelson Jr (Gertrude Parsons)',
  'female',
  45.0,
  52.5542),
 (1, 0, 'Klaber, Mr. Herman', 'male', None, 26.55),
 (1, 1, 'Kreuchen, Miss. Emilie', 'female', 39.0, 211.3375),
 (1, 1, 'Leader, Dr. Alice (Farnham)', 'female', 49.0, 25.9292),
 (1, 1, 'LeRoy, Miss. Bertha', 'female', 30.0, 106.425),
 (1, 1, 'Lesurer, Mr. Gustave J', 'male', 35.0, 512.3292),
 (1, 0, 'Lewy, Mr. Ervin G', 'male', None, 27.7208),
 (1,
  0,
  'Lindeberg-Lind, Mr. Erik Gustaf ("Mr Edward Lingrey")',
  'male',
  42.0,
  26.55),
 (1, 1, 'Lindstrom, Mrs. Carl Johan (Sigrid Posse)', 'female', 55.0, 27.7208),
 (1, 1, 'Lines, Miss. Mary Conover', 'female', 16.0, 39.4),
 (1,
  1,
  'Lines, Mrs. Ernest H (Elizabeth Lindsey James)',
  'female',
  51.0,
  39.4),
 (1, 0, 'Long, Mr. Milton Clyde', 'male', 29.0, 30.0),
 (1, 1, 'Longley, Miss. Gretchen Fiske', 'female', 21.0, 77.9583),
 (1, 0, 'Loring, Mr. Joseph Holland', 'male', 30.0, 45.5),
 (1, 1, 'Lurette, Miss. Elise', 'female', 58.0, 146.5208),
 (1, 1, 'Madill, Miss. Georgette Alexandra', 'female', 15.0, 211.3375),
 (1, 0, 'Maguire, Mr. John Edward', 'male', 30.0, 26.0),
 (1, 1, 'Maioni, Miss. Roberta', 'female', 16.0, 86.5),
 (1, 1, 'Marechal, Mr. Pierre', 'male', None, 29.7),
 (1, 0, 'Marvin, Mr. Daniel Warner', 'male', 19.0, 53.1),
 (1,
  1,
  'Marvin, Mrs. Daniel Warner (Mary Graham Carmichael Farquarson)',
  'female',
  18.0,
  53.1),
 (1,
  1,
  'Mayne, Mlle. Berthe Antonine ("Mrs de Villiers")',
  'female',
  24.0,
  49.5042),
 (1, 0, 'McCaffry, Mr. Thomas Francis', 'male', 46.0, 75.2417),
 (1, 0, 'McCarthy, Mr. Timothy J', 'male', 54.0, 51.8625),
 (1, 1, 'McGough, Mr. James Robert', 'male', 36.0, 26.2875),
 (1, 0, 'Meyer, Mr. Edgar Joseph', 'male', 28.0, 82.1708),
 (1, 1, 'Meyer, Mrs. Edgar Joseph (Leila Saks)', 'female', None, 82.1708),
 (1, 0, 'Millet, Mr. Francis Davis', 'male', 65.0, 26.55),
 (1, 0, 'Minahan, Dr. William Edward', 'male', 44.0, 90.0),
 (1, 1, 'Minahan, Miss. Daisy E', 'female', 33.0, 90.0),
 (1,
  1,
  'Minahan, Mrs. William Edward (Lillian E Thorpe)',
  'female',
  37.0,
  90.0),
 (1, 1, 'Mock, Mr. Philipp Edmund', 'male', 30.0, 57.75),
 (1, 0, 'Molson, Mr. Harry Markland', 'male', 55.0, 30.5),
 (1, 0, 'Moore, Mr. Clarence Bloomfield', 'male', 47.0, 42.4),
 (1, 0, 'Natsch, Mr. Charles H', 'male', 37.0, 29.7),
 (1, 1, 'Newell, Miss. Madeleine', 'female', 31.0, 113.275),
 (1, 1, 'Newell, Miss. Marjorie', 'female', 23.0, 113.275),
 (1, 0, 'Newell, Mr. Arthur Webster', 'male', 58.0, 113.275),
 (1, 1, 'Newsom, Miss. Helen Monypeny', 'female', 19.0, 26.2833),
 (1, 0, 'Nicholson, Mr. Arthur Ernest', 'male', 64.0, 26.0),
 (1, 1, 'Oliva y Ocana, Dona. Fermina', 'female', 39.0, 108.9),
 (1, 1, 'Omont, Mr. Alfred Fernand', 'male', None, 25.7417),
 (1, 1, 'Ostby, Miss. Helene Ragnhild', 'female', 22.0, 61.9792),
 (1, 0, 'Ostby, Mr. Engelhart Cornelius', 'male', 65.0, 61.9792),
 (1, 0, 'Ovies y Rodriguez, Mr. Servando', 'male', 28.5, 27.7208),
 (1, 0, 'Parr, Mr. William Henry Marsh', 'male', None, 0.0),
 (1, 0, 'Partner, Mr. Austen', 'male', 45.5, 28.5),
 (1, 0, 'Payne, Mr. Vivian Ponsonby', 'male', 23.0, 93.5),
 (1, 0, 'Pears, Mr. Thomas Clinton', 'male', 29.0, 66.6),
 (1, 1, 'Pears, Mrs. Thomas (Edith Wearne)', 'female', 22.0, 66.6),
 (1, 0, 'Penasco y Castellana, Mr. Victor de Satode', 'male', 18.0, 108.9),
 (1,
  1,
  'Penasco y Castellana, Mrs. Victor de Satode (Maria Josefa Perez de Soto y Vallejo)',
  'female',
  17.0,
  108.9),
 (1, 1, 'Perreault, Miss. Anne', 'female', 30.0, 93.5),
 (1, 1, 'Peuchen, Major. Arthur Godfrey', 'male', 52.0, 30.5),
 (1, 0, 'Porter, Mr. Walter Chamberlain', 'male', 47.0, 52.0),
 (1,
  1,
  'Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)',
  'female',
  56.0,
  83.1583),
 (1, 0, 'Reuchlin, Jonkheer. John George', 'male', 38.0, 0.0),
 (1, 1, 'Rheims, Mr. George Alexander Lucien', 'male', None, 39.6),
 (1, 0, 'Ringhini, Mr. Sante', 'male', 22.0, 135.6333),
 (1, 0, 'Robbins, Mr. Victor', 'male', None, 227.525),
 (1,
  1,
  'Robert, Mrs. Edward Scott (Elisabeth Walton McMillan)',
  'female',
  43.0,
  211.3375),
 (1, 0, 'Roebling, Mr. Washington Augustus II', 'male', 31.0, 50.4958),
 (1, 1, 'Romaine, Mr. Charles Hallace ("Mr C Rolmane")', 'male', 45.0, 26.55),
 (1, 0, 'Rood, Mr. Hugh Roscoe', 'male', None, 50.0),
 (1, 1, 'Rosenbaum, Miss. Edith Louise', 'female', 33.0, 27.7208),
 (1, 0, 'Rosenshine, Mr. George ("Mr George Thorne")', 'male', 46.0, 79.2),
 (1, 0, 'Ross, Mr. John Hugo', 'male', 36.0, 40.125),
 (1,
  1,
  'Rothes, the Countess. of (Lucy Noel Martha Dyer-Edwards)',
  'female',
  33.0,
  86.5),
 (1, 0, 'Rothschild, Mr. Martin', 'male', 55.0, 59.4),
 (1,
  1,
  'Rothschild, Mrs. Martin (Elizabeth L. Barrett)',
  'female',
  54.0,
  59.4),
 (1, 0, 'Rowe, Mr. Alfred G', 'male', 33.0, 26.55),
 (1, 1, 'Ryerson, Master. John Borie', 'male', 13.0, 262.375),
 (1, 1, 'Ryerson, Miss. Emily Borie', 'female', 18.0, 262.375),
 (1, 1, 'Ryerson, Miss. Susan Parker "Suzette"', 'female', 21.0, 262.375),
 (1, 0, 'Ryerson, Mr. Arthur Larned', 'male', 61.0, 262.375),
 (1,
  1,
  'Ryerson, Mrs. Arthur Larned (Emily Maria Borie)',
  'female',
  48.0,
  262.375),
 (1, 1, 'Saalfeld, Mr. Adolphe', 'male', None, 30.5),
 (1, 1, 'Sagesser, Mlle. Emma', 'female', 24.0, 69.3),
 (1, 1, 'Salomon, Mr. Abraham L', 'male', None, 26.0),
 (1, 1, 'Schabert, Mrs. Paul (Emma Mock)', 'female', 35.0, 57.75),
 (1, 1, 'Serepeca, Miss. Augusta', 'female', 30.0, 31.0),
 (1, 1, 'Seward, Mr. Frederic Kimber', 'male', 34.0, 26.55),
 (1, 1, 'Shutes, Miss. Elizabeth W', 'female', 40.0, 153.4625),
 (1, 1, 'Silverthorne, Mr. Spencer Victor', 'male', 35.0, 26.2875),
 (1, 0, 'Silvey, Mr. William Baird', 'male', 50.0, 55.9),
 (1, 1, 'Silvey, Mrs. William Baird (Alice Munger)', 'female', 39.0, 55.9),
 (1, 1, 'Simonius-Blumer, Col. Oberst Alfons', 'male', 56.0, 35.5),
 (1, 1, 'Sloper, Mr. William Thompson', 'male', 28.0, 35.5),
 (1, 0, 'Smart, Mr. John Montgomery', 'male', 56.0, 26.55),
 (1, 0, 'Smith, Mr. James Clinch', 'male', 56.0, 30.6958),
 (1, 0, 'Smith, Mr. Lucien Philip', 'male', 24.0, 60.0),
 (1, 0, 'Smith, Mr. Richard William', 'male', None, 26.0),
 (1,
  1,
  'Smith, Mrs. Lucien Philip (Mary Eloise Hughes)',
  'female',
  18.0,
  60.0),
 (1, 1, 'Snyder, Mr. John Pillsbury', 'male', 24.0, 82.2667),
 (1,
  1,
  'Snyder, Mrs. John Pillsbury (Nelle Stevenson)',
  'female',
  23.0,
  82.2667),
 (1, 1, 'Spedden, Master. Robert Douglas', 'male', 6.0, 134.5),
 (1, 1, 'Spedden, Mr. Frederic Oakley', 'male', 45.0, 134.5),
 (1,
  1,
  'Spedden, Mrs. Frederic Oakley (Margaretta Corning Stone)',
  'female',
  40.0,
  134.5),
 (1, 0, 'Spencer, Mr. William Augustus', 'male', 57.0, 146.5208),
 (1,
  1,
  'Spencer, Mrs. William Augustus (Marie Eugenie)',
  'female',
  None,
  146.5208),
 (1, 1, 'Stahelin-Maeglin, Dr. Max', 'male', 32.0, 30.5),
 (1, 0, 'Stead, Mr. William Thomas', 'male', 62.0, 26.55),
 (1, 1, 'Stengel, Mr. Charles Emil Henry', 'male', 54.0, 55.4417),
 (1,
  1,
  'Stengel, Mrs. Charles Emil Henry (Annie May Morris)',
  'female',
  43.0,
  55.4417),
 (1,
  1,
  'Stephenson, Mrs. Walter Bertram (Martha Eustis)',
  'female',
  52.0,
  78.2667),
 (1, 0, 'Stewart, Mr. Albert A', 'male', None, 27.7208),
 (1, 1, 'Stone, Mrs. George Nelson (Martha Evelyn)', 'female', 62.0, 80.0),
 (1, 0, 'Straus, Mr. Isidor', 'male', 67.0, 221.7792),
 (1, 0, 'Straus, Mrs. Isidor (Rosalie Ida Blun)', 'female', 63.0, 221.7792),
 (1, 0, 'Sutton, Mr. Frederick', 'male', 61.0, 32.3208),
 (1,
  1,
  'Swift, Mrs. Frederick Joel (Margaret Welles Barron)',
  'female',
  48.0,
  25.9292),
 (1, 1, 'Taussig, Miss. Ruth', 'female', 18.0, 79.65),
 (1, 0, 'Taussig, Mr. Emil', 'male', 52.0, 79.65),
 (1, 1, 'Taussig, Mrs. Emil (Tillie Mandelbaum)', 'female', 39.0, 79.65),

In [23]:
c.execute("select * from titanic").fetchall()

[(1, 1, 'Allen, Miss. Elisabeth Walton', 'female', 29.0, 211.3375),
 (1, 1, 'Allison, Master. Hudson Trevor', 'male', 0.9167, 151.55),
 (1, 0, 'Allison, Miss. Helen Loraine', 'female', 2.0, 151.55),
 (1, 0, 'Allison, Mr. Hudson Joshua Creighton', 'male', 30.0, 151.55),
 (1,
  0,
  'Allison, Mrs. Hudson J C (Bessie Waldo Daniels)',
  'female',
  25.0,
  151.55),
 (1, 1, 'Anderson, Mr. Harry', 'male', 48.0, 26.55),
 (1, 1, 'Andrews, Miss. Kornelia Theodosia', 'female', 63.0, 77.9583),
 (1, 0, 'Andrews, Mr. Thomas Jr', 'male', 39.0, 0.0),
 (1,
  1,
  'Appleton, Mrs. Edward Dale (Charlotte Lamson)',
  'female',
  53.0,
  51.4792),
 (1, 0, 'Artagaveytia, Mr. Ramon', 'male', 71.0, 49.5042),
 (1, 0, 'Astor, Col. John Jacob', 'male', 47.0, 227.525),
 (1,
  1,
  'Astor, Mrs. John Jacob (Madeleine Talmadge Force)',
  'female',
  18.0,
  227.525),
 (1, 1, 'Aubart, Mme. Leontine Pauline', 'female', 24.0, 69.3),
 (1, 1, 'Barber, Miss. Ellen "Nellie"', 'female', 26.0, 78.85),
 (1, 1, 'Barkworth, Mr. Algernon Henry Wilson', 'male', 80.0, 30.0),
 (1, 0, 'Baumann, Mr. John D', 'male', None, 25.925),
 (1, 0, 'Baxter, Mr. Quigg Edmond', 'male', 24.0, 247.5208),
 (1,
  1,
  'Baxter, Mrs. James (Helene DeLaudeniere Chaput)',
  'female',
  50.0,
  247.5208),
 (1, 1, 'Bazzani, Miss. Albina', 'female', 32.0, 76.2917),
 (1, 0, 'Beattie, Mr. Thomson', 'male', 36.0, 75.2417),
 (1, 1, 'Beckwith, Mr. Richard Leonard', 'male', 37.0, 52.5542),
 (1,
  1,
  'Beckwith, Mrs. Richard Leonard (Sallie Monypeny)',
  'female',
  47.0,
  52.5542),
 (1, 1, 'Behr, Mr. Karl Howell', 'male', 26.0, 30.0),
 (1, 1, 'Bidois, Miss. Rosalie', 'female', 42.0, 227.525),
 (1, 1, 'Bird, Miss. Ellen', 'female', 29.0, 221.7792),
 (1, 0, 'Birnbaum, Mr. Jakob', 'male', 25.0, 26.0),
 (1, 1, 'Bishop, Mr. Dickinson H', 'male', 25.0, 91.0792),
 (1, 1, 'Bishop, Mrs. Dickinson H (Helen Walton)', 'female', 19.0, 91.0792),
 (1, 1, 'Bissette, Miss. Amelia', 'female', 35.0, 135.6333),
 (1, 1, 'Bjornstrom-Steffansson, Mr. Mauritz Hakan', 'male', 28.0, 26.55),
 (1, 0, 'Blackwell, Mr. Stephen Weart', 'male', 45.0, 35.5),
 (1, 1, 'Blank, Mr. Henry', 'male', 40.0, 31.0),
 (1, 1, 'Bonnell, Miss. Caroline', 'female', 30.0, 164.8667),
 (1, 1, 'Bonnell, Miss. Elizabeth', 'female', 58.0, 26.55),
 (1, 0, 'Borebank, Mr. John James', 'male', 42.0, 26.55),
 (1, 1, 'Bowen, Miss. Grace Scott', 'female', 45.0, 262.375),
 (1, 1, 'Bowerman, Miss. Elsie Edith', 'female', 22.0, 55.0),
 (1, 1, 'Bradley, Mr. George ("George Arthur Brayton")', 'male', None, 26.55),
 (1, 0, 'Brady, Mr. John Bertram', 'male', 41.0, 30.5),
 (1, 0, 'Brandeis, Mr. Emil', 'male', 48.0, 50.4958),
 (1, 0, 'Brewe, Dr. Arthur Jackson', 'male', None, 39.6),
 (1, 1, 'Brown, Mrs. James Joseph (Margaret Tobin)', 'female', 44.0, 27.7208),
 (1,
  1,
  'Brown, Mrs. John Murray (Caroline Lane Lamson)',
  'female',
  59.0,
  51.4792),
 (1,
  1,
  'Bucknell, Mrs. William Robert (Emma Eliza Ward)',
  'female',
  60.0,
  76.2917),
 (1, 1, 'Burns, Miss. Elizabeth Margaret', 'female', 41.0, 134.5),
 (1, 0, 'Butt, Major. Archibald Willingham', 'male', 45.0, 26.55),
 (1, 0, 'Cairns, Mr. Alexander', 'male', None, 31.0),
 (1, 1, 'Calderhead, Mr. Edward Pennington', 'male', 42.0, 26.2875),
 (1,
  1,
  'Candee, Mrs. Edward (Helen Churchill Hungerford)',
  'female',
  53.0,
  27.4458),
 (1, 1, 'Cardeza, Mr. Thomas Drake Martinez', 'male', 36.0, 512.3292),
 (1,
  1,
  'Cardeza, Mrs. James Warburton Martinez (Charlotte Wardle Drake)',
  'female',
  58.0,
  512.3292),
 (1, 0, 'Carlsson, Mr. Frans Olof', 'male', 33.0, 5.0),
 (1, 0, 'Carrau, Mr. Francisco M', 'male', 28.0, 47.1),
 (1, 0, 'Carrau, Mr. Jose Pedro', 'male', 17.0, 47.1),
 (1, 1, 'Carter, Master. William Thornton II', 'male', 11.0, 120.0),
 (1, 1, 'Carter, Miss. Lucile Polk', 'female', 14.0, 120.0),
 (1, 1, 'Carter, Mr. William Ernest', 'male', 36.0, 120.0),
 (1, 1, 'Carter, Mrs. William Ernest (Lucile Polk)', 'female', 36.0, 120.0),
 (1, 0, 'Case, Mr. Howard Brown', 'male', 49.0, 26.0),
 (1,
  1,
  'Cassebeer, Mrs. Henry Arthur Jr (Eleanor Genevieve Fosdick)',
  'female',
  None,
  27.7208),
 (1, 0, 'Cavendish, Mr. Tyrell William', 'male', 36.0, 78.85),
 (1,
  1,
  'Cavendish, Mrs. Tyrell William (Julia Florence Siegel)',
  'female',
  76.0,
  78.85),
 (1, 0, 'Chaffee, Mr. Herbert Fuller', 'male', 46.0, 61.175),
 (1,
  1,
  'Chaffee, Mrs. Herbert Fuller (Carrie Constance Toogood)',
  'female',
  47.0,
  61.175),
 (1, 1, 'Chambers, Mr. Norman Campbell', 'male', 27.0, 53.1),
 (1,
  1,
  'Chambers, Mrs. Norman Campbell (Bertha Griggs)',
  'female',
  33.0,
  53.1),
 (1, 1, 'Chaudanson, Miss. Victorine', 'female', 36.0, 262.375),
 (1, 1, 'Cherry, Miss. Gladys', 'female', 30.0, 86.5),
 (1, 1, 'Chevre, Mr. Paul Romaine', 'male', 45.0, 29.7),
 (1, 1, 'Chibnall, Mrs. (Edith Martha Bowerman)', 'female', None, 55.0),
 (1, 0, 'Chisholm, Mr. Roderick Robert Crispin', 'male', None, 0.0),
 (1, 0, 'Clark, Mr. Walter Miller', 'male', 27.0, 136.7792),
 (1,
  1,
  'Clark, Mrs. Walter Miller (Virginia McDowell)',
  'female',
  26.0,
  136.7792),
 (1, 1, 'Cleaver, Miss. Alice', 'female', 22.0, 151.55),
 (1, 0, 'Clifford, Mr. George Quincy', 'male', None, 52.0),
 (1, 0, 'Colley, Mr. Edward Pomeroy', 'male', 47.0, 25.5875),
 (1, 1, 'Compton, Miss. Sara Rebecca', 'female', 39.0, 83.1583),
 (1, 0, 'Compton, Mr. Alexander Taylor Jr', 'male', 37.0, 83.1583),
 (1,
  1,
  'Compton, Mrs. Alexander Taylor (Mary Eliza Ingersoll)',
  'female',
  64.0,
  83.1583),
 (1,
  1,
  'Cornell, Mrs. Robert Clifford (Malvina Helen Lamson)',
  'female',
  55.0,
  25.7),
 (1, 0, 'Crafton, Mr. John Bertram', 'male', None, 26.55),
 (1, 0, 'Crosby, Capt. Edward Gifford', 'male', 70.0, 71.0),
 (1, 1, 'Crosby, Miss. Harriet R', 'female', 36.0, 71.0),
 (1,
  1,
  'Crosby, Mrs. Edward Gifford (Catherine Elizabeth Halstead)',
  'female',
  64.0,
  26.55),
 (1, 0, 'Cumings, Mr. John Bradley', 'male', 39.0, 71.2833),
 (1,
  1,
  'Cumings, Mrs. John Bradley (Florence Briggs Thayer)',
  'female',
  38.0,
  71.2833),
 (1, 1, 'Daly, Mr. Peter Denis ', 'male', 51.0, 26.55),
 (1, 1, 'Daniel, Mr. Robert Williams', 'male', 27.0, 30.5),
 (1, 1, 'Daniels, Miss. Sarah', 'female', 33.0, 151.55),
 (1, 0, 'Davidson, Mr. Thornton', 'male', 31.0, 52.0),
 (1, 1, 'Davidson, Mrs. Thornton (Orian Hays)', 'female', 27.0, 52.0),
 (1, 1, 'Dick, Mr. Albert Adrian', 'male', 31.0, 57.0),
 (1, 1, 'Dick, Mrs. Albert Adrian (Vera Gillespie)', 'female', 17.0, 57.0),
 (1, 1, 'Dodge, Dr. Washington', 'male', 53.0, 81.8583),
 (1, 1, 'Dodge, Master. Washington', 'male', 4.0, 81.8583),
 (1, 1, 'Dodge, Mrs. Washington (Ruth Vidaver)', 'female', 54.0, 81.8583),
 (1, 0, 'Douglas, Mr. Walter Donald', 'male', 50.0, 106.425),
 (1,
  1,
  'Douglas, Mrs. Frederick Charles (Mary Helene Baxter)',
  'female',
  27.0,
  247.5208),
 (1,
  1,
  'Douglas, Mrs. Walter Donald (Mahala Dutton)',
  'female',
  48.0,
  106.425),
 (1,
  1,
  'Duff Gordon, Lady. (Lucille Christiana Sutherland) ("Mrs Morgan")',
  'female',
  48.0,
  39.6),
 (1, 1, 'Duff Gordon, Sir. Cosmo Edmund ("Mr Morgan")', 'male', 49.0, 56.9292),
 (1, 0, 'Dulles, Mr. William Crothers', 'male', 39.0, 29.7),
 (1, 1, 'Earnshaw, Mrs. Boulton (Olive Potter)', 'female', 23.0, 83.1583),
 (1, 1, 'Endres, Miss. Caroline Louise', 'female', 38.0, 227.525),
 (1, 1, 'Eustis, Miss. Elizabeth Mussey', 'female', 54.0, 78.2667),
 (1, 0, 'Evans, Miss. Edith Corse', 'female', 36.0, 31.6792),
 (1, 0, 'Farthing, Mr. John', 'male', None, 221.7792),
 (1, 1, 'Flegenheim, Mrs. Alfred (Antoinette)', 'female', None, 31.6833),
 (1, 1, 'Fleming, Miss. Margaret', 'female', None, 110.8833),
 (1, 1, 'Flynn, Mr. John Irwin ("Irving")', 'male', 36.0, 26.3875),
 (1, 0, 'Foreman, Mr. Benjamin Laventall', 'male', 30.0, 27.75),
 (1, 1, 'Fortune, Miss. Alice Elizabeth', 'female', 24.0, 263.0),
 (1, 1, 'Fortune, Miss. Ethel Flora', 'female', 28.0, 263.0),
 (1, 1, 'Fortune, Miss. Mabel Helen', 'female', 23.0, 263.0),
 (1, 0, 'Fortune, Mr. Charles Alexander', 'male', 19.0, 263.0),
 (1, 0, 'Fortune, Mr. Mark', 'male', 64.0, 263.0),
 (1, 1, 'Fortune, Mrs. Mark (Mary McDougald)', 'female', 60.0, 263.0),
 (1, 1, 'Francatelli, Miss. Laura Mabel', 'female', 30.0, 56.9292),
 (1, 0, 'Franklin, Mr. Thomas Parham', 'male', None, 26.55),
 (1, 1, 'Frauenthal, Dr. Henry William', 'male', 50.0, 133.65),
 (1, 1, 'Frauenthal, Mr. Isaac Gerald', 'male', 43.0, 27.7208),
 (1,
  1,
  'Frauenthal, Mrs. Henry William (Clara Heinsheimer)',
  'female',
  None,
  133.65),
 (1, 1, 'Frolicher, Miss. Hedwig Margaritha', 'female', 22.0, 49.5),
 (1, 1, 'Frolicher-Stehli, Mr. Maxmillian', 'male', 60.0, 79.2),
 (1,
  1,
  'Frolicher-Stehli, Mrs. Maxmillian (Margaretha Emerentia Stehli)',
  'female',
  48.0,
  79.2),
 (1, 0, 'Fry, Mr. Richard', 'male', None, 0.0),
 (1, 0, 'Futrelle, Mr. Jacques Heath', 'male', 37.0, 53.1),
 (1, 1, 'Futrelle, Mrs. Jacques Heath (Lily May Peel)', 'female', 35.0, 53.1),
 (1, 0, 'Gee, Mr. Arthur H', 'male', 47.0, 38.5),
 (1, 1, 'Geiger, Miss. Amalie', 'female', 35.0, 211.5),
 (1, 1, 'Gibson, Miss. Dorothy Winifred', 'female', 22.0, 59.4),
 (1, 1, 'Gibson, Mrs. Leonard (Pauline C Boeson)', 'female', 45.0, 59.4),
 (1, 0, 'Giglio, Mr. Victor', 'male', 24.0, 79.2),
 (1, 1, 'Goldenberg, Mr. Samuel L', 'male', 49.0, 89.1042),
 (1,
  1,
  'Goldenberg, Mrs. Samuel L (Edwiga Grabowska)',
  'female',
  None,
  89.1042),
 (1, 0, 'Goldschmidt, Mr. George B', 'male', 71.0, 34.6542),
 (1, 1, 'Gracie, Col. Archibald IV', 'male', 53.0, 28.5),
 (1, 1, 'Graham, Miss. Margaret Edith', 'female', 19.0, 30.0),
 (1, 0, 'Graham, Mr. George Edward', 'male', 38.0, 153.4625),
 (1,
  1,
  'Graham, Mrs. William Thompson (Edith Junkins)',
  'female',
  58.0,
  153.4625),
 (1, 1, 'Greenfield, Mr. William Bertram', 'male', 23.0, 63.3583),
 (1,
  1,
  'Greenfield, Mrs. Leo David (Blanche Strouse)',
  'female',
  45.0,
  63.3583),
 (1, 0, 'Guggenheim, Mr. Benjamin', 'male', 46.0, 79.2),
 (1, 1, 'Harder, Mr. George Achilles', 'male', 25.0, 55.4417),
 (1,
  1,
  'Harder, Mrs. George Achilles (Dorothy Annan)',
  'female',
  25.0,
  55.4417),
 (1, 1, 'Harper, Mr. Henry Sleeper', 'male', 48.0, 76.7292),
 (1, 1, 'Harper, Mrs. Henry Sleeper (Myna Haxtun)', 'female', 49.0, 76.7292),
 (1, 0, 'Harrington, Mr. Charles H', 'male', None, 42.4),
 (1, 0, 'Harris, Mr. Henry Birkhardt', 'male', 45.0, 83.475),
 (1,
  1,
  'Harris, Mrs. Henry Birkhardt (Irene Wallach)',
  'female',
  35.0,
  83.475),
 (1, 0, 'Harrison, Mr. William', 'male', 40.0, 0.0),
 (1, 1, 'Hassab, Mr. Hammad', 'male', 27.0, 76.7292),
 (1, 1, 'Hawksford, Mr. Walter James', 'male', None, 30.0),
 (1, 1, 'Hays, Miss. Margaret Bechstein', 'female', 24.0, 83.1583),
 (1, 0, 'Hays, Mr. Charles Melville', 'male', 55.0, 93.5),
 (1,
  1,
  'Hays, Mrs. Charles Melville (Clara Jennings Gregg)',
  'female',
  52.0,
  93.5),
 (1, 0, 'Head, Mr. Christopher', 'male', 42.0, 42.5),
 (1, 0, 'Hilliard, Mr. Herbert Henry', 'male', None, 51.8625),
 (1, 0, 'Hipkins, Mr. William Edward', 'male', 55.0, 50.0),
 (1, 1, 'Hippach, Miss. Jean Gertrude', 'female', 16.0, 57.9792),
 (1,
  1,
  'Hippach, Mrs. Louis Albert (Ida Sophia Fischer)',
  'female',
  44.0,
  57.9792),
 (1, 1, 'Hogeboom, Mrs. John C (Anna Andrews)', 'female', 51.0, 77.9583),
 (1, 0, 'Holverson, Mr. Alexander Oskar', 'male', 42.0, 52.0),
 (1,
  1,
  'Holverson, Mrs. Alexander Oskar (Mary Aline Towner)',
  'female',
  35.0,
  52.0),
 (1, 1, 'Homer, Mr. Harry ("Mr E Haven")', 'male', 35.0, 26.55),
 (1, 1, 'Hoyt, Mr. Frederick Maxfield', 'male', 38.0, 90.0),
 (1, 0, 'Hoyt, Mr. William Fisher', 'male', None, 30.6958),
 (1,
  1,
  'Hoyt, Mrs. Frederick Maxfield (Jane Anne Forby)',
  'female',
  35.0,
  90.0),
 (1, 1, 'Icard, Miss. Amelie', 'female', 38.0, 80.0),
 (1, 0, 'Isham, Miss. Ann Elizabeth', 'female', 50.0, 28.7125),
 (1, 1, 'Ismay, Mr. Joseph Bruce', 'male', 49.0, 0.0),
 (1, 0, 'Jones, Mr. Charles Cresson', 'male', 46.0, 26.0),
 (1, 0, 'Julian, Mr. Henry Forbes', 'male', 50.0, 26.0),
 (1, 0, 'Keeping, Mr. Edwin', 'male', 32.5, 211.5),
 (1, 0, 'Kent, Mr. Edward Austin', 'male', 58.0, 29.7),
 (1, 0, 'Kenyon, Mr. Frederick R', 'male', 41.0, 51.8625),
 (1, 1, 'Kenyon, Mrs. Frederick R (Marion)', 'female', None, 51.8625),
 (1, 1, 'Kimball, Mr. Edwin Nelson Jr', 'male', 42.0, 52.5542),
 (1,
  1,
  'Kimball, Mrs. Edwin Nelson Jr (Gertrude Parsons)',
  'female',
  45.0,
  52.5542),
 (1, 0, 'Klaber, Mr. Herman', 'male', None, 26.55),
 (1, 1, 'Kreuchen, Miss. Emilie', 'female', 39.0, 211.3375),
 (1, 1, 'Leader, Dr. Alice (Farnham)', 'female', 49.0, 25.9292),
 (1, 1, 'LeRoy, Miss. Bertha', 'female', 30.0, 106.425),
 (1, 1, 'Lesurer, Mr. Gustave J', 'male', 35.0, 512.3292),
 (1, 0, 'Lewy, Mr. Ervin G', 'male', None, 27.7208),
 (1,
  0,
  'Lindeberg-Lind, Mr. Erik Gustaf ("Mr Edward Lingrey")',
  'male',
  42.0,
  26.55),
 (1, 1, 'Lindstrom, Mrs. Carl Johan (Sigrid Posse)', 'female', 55.0, 27.7208),
 (1, 1, 'Lines, Miss. Mary Conover', 'female', 16.0, 39.4),
 (1,
  1,
  'Lines, Mrs. Ernest H (Elizabeth Lindsey James)',
  'female',
  51.0,
  39.4),
 (1, 0, 'Long, Mr. Milton Clyde', 'male', 29.0, 30.0),
 (1, 1, 'Longley, Miss. Gretchen Fiske', 'female', 21.0, 77.9583),
 (1, 0, 'Loring, Mr. Joseph Holland', 'male', 30.0, 45.5),
 (1, 1, 'Lurette, Miss. Elise', 'female', 58.0, 146.5208),
 (1, 1, 'Madill, Miss. Georgette Alexandra', 'female', 15.0, 211.3375),
 (1, 0, 'Maguire, Mr. John Edward', 'male', 30.0, 26.0),
 (1, 1, 'Maioni, Miss. Roberta', 'female', 16.0, 86.5),
 (1, 1, 'Marechal, Mr. Pierre', 'male', None, 29.7),
 (1, 0, 'Marvin, Mr. Daniel Warner', 'male', 19.0, 53.1),
 (1,
  1,
  'Marvin, Mrs. Daniel Warner (Mary Graham Carmichael Farquarson)',
  'female',
  18.0,
  53.1),
 (1,
  1,
  'Mayne, Mlle. Berthe Antonine ("Mrs de Villiers")',
  'female',
  24.0,
  49.5042),
 (1, 0, 'McCaffry, Mr. Thomas Francis', 'male', 46.0, 75.2417),
 (1, 0, 'McCarthy, Mr. Timothy J', 'male', 54.0, 51.8625),
 (1, 1, 'McGough, Mr. James Robert', 'male', 36.0, 26.2875),
 (1, 0, 'Meyer, Mr. Edgar Joseph', 'male', 28.0, 82.1708),
 (1, 1, 'Meyer, Mrs. Edgar Joseph (Leila Saks)', 'female', None, 82.1708),
 (1, 0, 'Millet, Mr. Francis Davis', 'male', 65.0, 26.55),
 (1, 0, 'Minahan, Dr. William Edward', 'male', 44.0, 90.0),
 (1, 1, 'Minahan, Miss. Daisy E', 'female', 33.0, 90.0),
 (1,
  1,
  'Minahan, Mrs. William Edward (Lillian E Thorpe)',
  'female',
  37.0,
  90.0),
 (1, 1, 'Mock, Mr. Philipp Edmund', 'male', 30.0, 57.75),
 (1, 0, 'Molson, Mr. Harry Markland', 'male', 55.0, 30.5),
 (1, 0, 'Moore, Mr. Clarence Bloomfield', 'male', 47.0, 42.4),
 (1, 0, 'Natsch, Mr. Charles H', 'male', 37.0, 29.7),
 (1, 1, 'Newell, Miss. Madeleine', 'female', 31.0, 113.275),
 (1, 1, 'Newell, Miss. Marjorie', 'female', 23.0, 113.275),
 (1, 0, 'Newell, Mr. Arthur Webster', 'male', 58.0, 113.275),
 (1, 1, 'Newsom, Miss. Helen Monypeny', 'female', 19.0, 26.2833),
 (1, 0, 'Nicholson, Mr. Arthur Ernest', 'male', 64.0, 26.0),
 (1, 1, 'Oliva y Ocana, Dona. Fermina', 'female', 39.0, 108.9),
 (1, 1, 'Omont, Mr. Alfred Fernand', 'male', None, 25.7417),
 (1, 1, 'Ostby, Miss. Helene Ragnhild', 'female', 22.0, 61.9792),
 (1, 0, 'Ostby, Mr. Engelhart Cornelius', 'male', 65.0, 61.9792),
 (1, 0, 'Ovies y Rodriguez, Mr. Servando', 'male', 28.5, 27.7208),
 (1, 0, 'Parr, Mr. William Henry Marsh', 'male', None, 0.0),
 (1, 0, 'Partner, Mr. Austen', 'male', 45.5, 28.5),
 (1, 0, 'Payne, Mr. Vivian Ponsonby', 'male', 23.0, 93.5),
 (1, 0, 'Pears, Mr. Thomas Clinton', 'male', 29.0, 66.6),
 (1, 1, 'Pears, Mrs. Thomas (Edith Wearne)', 'female', 22.0, 66.6),
 (1, 0, 'Penasco y Castellana, Mr. Victor de Satode', 'male', 18.0, 108.9),
 (1,
  1,
  'Penasco y Castellana, Mrs. Victor de Satode (Maria Josefa Perez de Soto y Vallejo)',
  'female',
  17.0,
  108.9),
 (1, 1, 'Perreault, Miss. Anne', 'female', 30.0, 93.5),
 (1, 1, 'Peuchen, Major. Arthur Godfrey', 'male', 52.0, 30.5),
 (1, 0, 'Porter, Mr. Walter Chamberlain', 'male', 47.0, 52.0),
 (1,
  1,
  'Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)',
  'female',
  56.0,
  83.1583),
 (1, 0, 'Reuchlin, Jonkheer. John George', 'male', 38.0, 0.0),
 (1, 1, 'Rheims, Mr. George Alexander Lucien', 'male', None, 39.6),
 (1, 0, 'Ringhini, Mr. Sante', 'male', 22.0, 135.6333),
 (1, 0, 'Robbins, Mr. Victor', 'male', None, 227.525),
 (1,
  1,
  'Robert, Mrs. Edward Scott (Elisabeth Walton McMillan)',
  'female',
  43.0,
  211.3375),
 (1, 0, 'Roebling, Mr. Washington Augustus II', 'male', 31.0, 50.4958),
 (1, 1, 'Romaine, Mr. Charles Hallace ("Mr C Rolmane")', 'male', 45.0, 26.55),
 (1, 0, 'Rood, Mr. Hugh Roscoe', 'male', None, 50.0),
 (1, 1, 'Rosenbaum, Miss. Edith Louise', 'female', 33.0, 27.7208),
 (1, 0, 'Rosenshine, Mr. George ("Mr George Thorne")', 'male', 46.0, 79.2),
 (1, 0, 'Ross, Mr. John Hugo', 'male', 36.0, 40.125),
 (1,
  1,
  'Rothes, the Countess. of (Lucy Noel Martha Dyer-Edwards)',
  'female',
  33.0,
  86.5),
 (1, 0, 'Rothschild, Mr. Martin', 'male', 55.0, 59.4),
 (1,
  1,
  'Rothschild, Mrs. Martin (Elizabeth L. Barrett)',
  'female',
  54.0,
  59.4),
 (1, 0, 'Rowe, Mr. Alfred G', 'male', 33.0, 26.55),
 (1, 1, 'Ryerson, Master. John Borie', 'male', 13.0, 262.375),
 (1, 1, 'Ryerson, Miss. Emily Borie', 'female', 18.0, 262.375),
 (1, 1, 'Ryerson, Miss. Susan Parker "Suzette"', 'female', 21.0, 262.375),
 (1, 0, 'Ryerson, Mr. Arthur Larned', 'male', 61.0, 262.375),
 (1,
  1,
  'Ryerson, Mrs. Arthur Larned (Emily Maria Borie)',
  'female',
  48.0,
  262.375),
 (1, 1, 'Saalfeld, Mr. Adolphe', 'male', None, 30.5),
 (1, 1, 'Sagesser, Mlle. Emma', 'female', 24.0, 69.3),
 (1, 1, 'Salomon, Mr. Abraham L', 'male', None, 26.0),
 (1, 1, 'Schabert, Mrs. Paul (Emma Mock)', 'female', 35.0, 57.75),
 (1, 1, 'Serepeca, Miss. Augusta', 'female', 30.0, 31.0),
 (1, 1, 'Seward, Mr. Frederic Kimber', 'male', 34.0, 26.55),
 (1, 1, 'Shutes, Miss. Elizabeth W', 'female', 40.0, 153.4625),
 (1, 1, 'Silverthorne, Mr. Spencer Victor', 'male', 35.0, 26.2875),
 (1, 0, 'Silvey, Mr. William Baird', 'male', 50.0, 55.9),
 (1, 1, 'Silvey, Mrs. William Baird (Alice Munger)', 'female', 39.0, 55.9),
 (1, 1, 'Simonius-Blumer, Col. Oberst Alfons', 'male', 56.0, 35.5),
 (1, 1, 'Sloper, Mr. William Thompson', 'male', 28.0, 35.5),
 (1, 0, 'Smart, Mr. John Montgomery', 'male', 56.0, 26.55),
 (1, 0, 'Smith, Mr. James Clinch', 'male', 56.0, 30.6958),
 (1, 0, 'Smith, Mr. Lucien Philip', 'male', 24.0, 60.0),
 (1, 0, 'Smith, Mr. Richard William', 'male', None, 26.0),
 (1,
  1,
  'Smith, Mrs. Lucien Philip (Mary Eloise Hughes)',
  'female',
  18.0,
  60.0),
 (1, 1, 'Snyder, Mr. John Pillsbury', 'male', 24.0, 82.2667),
 (1,
  1,
  'Snyder, Mrs. John Pillsbury (Nelle Stevenson)',
  'female',
  23.0,
  82.2667),
 (1, 1, 'Spedden, Master. Robert Douglas', 'male', 6.0, 134.5),
 (1, 1, 'Spedden, Mr. Frederic Oakley', 'male', 45.0, 134.5),
 (1,
  1,
  'Spedden, Mrs. Frederic Oakley (Margaretta Corning Stone)',
  'female',
  40.0,
  134.5),
 (1, 0, 'Spencer, Mr. William Augustus', 'male', 57.0, 146.5208),
 (1,
  1,
  'Spencer, Mrs. William Augustus (Marie Eugenie)',
  'female',
  None,
  146.5208),
 (1, 1, 'Stahelin-Maeglin, Dr. Max', 'male', 32.0, 30.5),
 (1, 0, 'Stead, Mr. William Thomas', 'male', 62.0, 26.55),
 (1, 1, 'Stengel, Mr. Charles Emil Henry', 'male', 54.0, 55.4417),
 (1,
  1,
  'Stengel, Mrs. Charles Emil Henry (Annie May Morris)',
  'female',
  43.0,
  55.4417),
 (1,
  1,
  'Stephenson, Mrs. Walter Bertram (Martha Eustis)',
  'female',
  52.0,
  78.2667),
 (1, 0, 'Stewart, Mr. Albert A', 'male', None, 27.7208),
 (1, 1, 'Stone, Mrs. George Nelson (Martha Evelyn)', 'female', 62.0, 80.0),
 (1, 0, 'Straus, Mr. Isidor', 'male', 67.0, 221.7792),
 (1, 0, 'Straus, Mrs. Isidor (Rosalie Ida Blun)', 'female', 63.0, 221.7792),
 (1, 0, 'Sutton, Mr. Frederick', 'male', 61.0, 32.3208),
 (1,
  1,
  'Swift, Mrs. Frederick Joel (Margaret Welles Barron)',
  'female',
  48.0,
  25.9292),
 (1, 1, 'Taussig, Miss. Ruth', 'female', 18.0, 79.65),
 (1, 0, 'Taussig, Mr. Emil', 'male', 52.0, 79.65),
 (1, 1, 'Taussig, Mrs. Emil (Tillie Mandelbaum)', 'female', 39.0, 79.65),

In [24]:
c.close()
conn.close()